/**
 * Generated by orval 🍺
 * Do not edit manually.
 * HCManagement | v1
 * OpenAPI spec version: 1.0.0
 */
import type { ChangePasswordRequestDto, VerifyCredentialsRequestDto } from "./schema.schemas";

import { fetchAndThrowAsync } from "../mutators/fetch";

export const getGetAccessCookieAsyncUrl = () => {
  return `/api/Authentication/GetAccessCookie`;
};

export const getAccessCookieAsync = async (
  verifyCredentialsRequestDto: VerifyCredentialsRequestDto,
  options?: Parameters<typeof fetchAndThrowAsync>[1],
): Promise<void> => {
  const getHeaders = (h?: NonNullable<RequestInit["headers"]>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
  return fetchAndThrowAsync<void>(getGetAccessCookieAsyncUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...getHeaders(options?.headers) },
    body: JSON.stringify(verifyCredentialsRequestDto),
  });
};

export const getClearAccessCookieAsyncUrl = () => {
  return `/api/Authentication/ClearAccessCookie`;
};

export const clearAccessCookieAsync = async (options?: Parameters<typeof fetchAndThrowAsync>[1]): Promise<void> => {
  return fetchAndThrowAsync<void>(getClearAccessCookieAsyncUrl(), {
    ...options,
    method: "POST",
  });
};

export const getCallerDetailAsyncUrl = () => {
  return `/api/Authentication/CallerDetail`;
};

export const callerDetailAsync = async (options?: Parameters<typeof fetchAndThrowAsync>[1]): Promise<void> => {
  return fetchAndThrowAsync<void>(getCallerDetailAsyncUrl(), {
    ...options,
    method: "GET",
  });
};

export const getChangePasswordAsyncUrl = () => {
  return `/api/Authentication/ChangePassword`;
};

export const changePasswordAsync = async (
  changePasswordRequestDto: ChangePasswordRequestDto,
  options?: Parameters<typeof fetchAndThrowAsync>[1],
): Promise<void> => {
  const getHeaders = (h?: NonNullable<RequestInit["headers"]>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
  return fetchAndThrowAsync<void>(getChangePasswordAsyncUrl(), {
    ...options,
    method: "PUT",
    headers: { "Content-Type": "application/json", ...getHeaders(options?.headers) },
    body: JSON.stringify(changePasswordRequestDto),
  });
};

export const getCheckAuthenticationStatusAsyncUrl = () => {
  return `/api/Authentication/CheckAuthenticationStatus`;
};

export const checkAuthenticationStatusAsync = async (
  options?: Parameters<typeof fetchAndThrowAsync>[1],
): Promise<void> => {
  return fetchAndThrowAsync<void>(getCheckAuthenticationStatusAsyncUrl(), {
    ...options,
    method: "POST",
  });
};
