/**
 * Generated by orval 🍺
 * Do not edit manually.
 * HCManagement | v1
 * OpenAPI spec version: 1.0.0
 */
import type {
  GetDisplayNamesAsync200One,
  GetDisplayNamesAsync200Three,
  GetDisplayNamesAsync200Two,
} from "./schema.schemas";

import { fetchAndThrowAsync } from "../mutators/fetch";

export const getGetDisplayNamesAsyncUrl = () => {
  return `/api/localization/display-names`;
};

export const getDisplayNamesAsync = async (
  options?: Parameters<typeof fetchAndThrowAsync>[1],
): Promise<GetDisplayNamesAsync200One | GetDisplayNamesAsync200Two | GetDisplayNamesAsync200Three> => {
  return fetchAndThrowAsync<GetDisplayNamesAsync200One | GetDisplayNamesAsync200Two | GetDisplayNamesAsync200Three>(
    getGetDisplayNamesAsyncUrl(),
    {
      ...options,
      method: "GET",
    },
  );
};
