/**
 * Generated by orval 🍺
 * Do not edit manually.
 * HCManagement | v1
 * OpenAPI spec version: 1.0.0
 */
import type {
  OrderDetailResponseDto,
  OrderListRequestDto,
  OrderListResponseDto,
  OrderUpsertRequestDto,
} from "./schema.schemas";

import { fetchAndThrowAsync } from "../mutators/fetch";

export const getGetListAsyncUrl = () => {
  return `/api/orders/list`;
};

export const getListAsync = async (
  orderListRequestDto: OrderListRequestDto,
  options?: Parameters<typeof fetchAndThrowAsync>[1],
): Promise<OrderListResponseDto> => {
  const getHeaders = (h?: NonNullable<RequestInit["headers"]>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
  return fetchAndThrowAsync<OrderListResponseDto>(getGetListAsyncUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...getHeaders(options?.headers) },
    body: JSON.stringify(orderListRequestDto),
  });
};

export const getGetDetailAsyncUrl = (id: number) => {
  return `/api/orders/${id}`;
};

export const getDetailAsync = async (
  id: number,
  options?: Parameters<typeof fetchAndThrowAsync>[1],
): Promise<OrderDetailResponseDto> => {
  return fetchAndThrowAsync<OrderDetailResponseDto>(getGetDetailAsyncUrl(id), {
    ...options,
    method: "GET",
  });
};

export const getUpdateAsyncUrl = (id: number) => {
  return `/api/orders/${id}`;
};

export const updateAsync = async (
  id: number,
  orderUpsertRequestDto: OrderUpsertRequestDto,
  options?: Parameters<typeof fetchAndThrowAsync>[1],
): Promise<OrderDetailResponseDto> => {
  const getHeaders = (h?: NonNullable<RequestInit["headers"]>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
  return fetchAndThrowAsync<OrderDetailResponseDto>(getUpdateAsyncUrl(id), {
    ...options,
    method: "PUT",
    headers: { "Content-Type": "application/json", ...getHeaders(options?.headers) },
    body: JSON.stringify(orderUpsertRequestDto),
  });
};

export const getDeleteAsyncUrl = (id: number) => {
  return `/api/orders/${id}`;
};

export const deleteAsync = async (id: number, options?: Parameters<typeof fetchAndThrowAsync>[1]): Promise<void> => {
  return fetchAndThrowAsync<void>(getDeleteAsyncUrl(id), {
    ...options,
    method: "DELETE",
  });
};

export const getCreateAsyncUrl = () => {
  return `/api/orders`;
};

export const createAsync = async (
  orderUpsertRequestDto: OrderUpsertRequestDto,
  options?: Parameters<typeof fetchAndThrowAsync>[1],
): Promise<OrderDetailResponseDto> => {
  const getHeaders = (h?: NonNullable<RequestInit["headers"]>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
  return fetchAndThrowAsync<OrderDetailResponseDto>(getCreateAsyncUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...getHeaders(options?.headers) },
    body: JSON.stringify(orderUpsertRequestDto),
  });
};

export const getFinishAsyncUrl = (id: number) => {
  return `/api/orders/${id}/finish`;
};

export const finishAsync = async (id: number, options?: Parameters<typeof fetchAndThrowAsync>[1]): Promise<void> => {
  return fetchAndThrowAsync<void>(getFinishAsyncUrl(id), {
    ...options,
    method: "PUT",
  });
};

export const getGetDefaultListParametersAsyncUrl = () => {
  return `/api/orders/default-list-parameters`;
};

export const getDefaultListParametersAsync = async (
  options?: Parameters<typeof fetchAndThrowAsync>[1],
): Promise<OrderListRequestDto> => {
  return fetchAndThrowAsync<OrderListRequestDto>(getGetDefaultListParametersAsyncUrl(), {
    ...options,
    method: "GET",
  });
};
