/**
 * Generated by orval 🍺
 * Do not edit manually.
 * HCManagement | v1
 * OpenAPI spec version: 1.0.0
 */
export type ChangePasswordRequestDto = {
  currentPassword: string;
  newPassword: string;
};

export type MenuCategoryBasicResponseDto = {
  id: number;
  name: string;
};

export type MenuCategoryUpsertRequestDto = {
  name: string;
  /** @nullable */
  index?: number | null;
};

export type MenuItemBasicResponseDto = {
  id: number;
  name: string;
  unit: string;
  defaultAmountBeforeVatPerUnit: number;
  defaultVatPercentagePerUnit: number;
  isDeleted: boolean;
};

export type UserBasicResponseDto = {
  id: number;
  userName: string;
  isDeleted: boolean;
};

export type MenuItemDetailResponseDto = {
  id: number;
  name: string;
  unit: string;
  defaultAmountBeforeVatPerUnit: number;
  defaultVatPercentagePerUnit: number;
  createdUser: UserBasicResponseDto;
  createdDateTime: string;
  lastUpdatedUser: UserBasicResponseDto | null;
  lastUpdatedDateTime: string | null;
  deletedUser: UserBasicResponseDto | null;
  deletedDateTime: string | null;
};

export type MenuItemListSortingCriterion = number;

export type MenuItemListRequestDto = {
  sortByAscending?: boolean;
  sortByCriterion?: MenuItemListSortingCriterion;
  /** @nullable */
  searchContent?: string | null;
  /** @nullable */
  categoryId?: number | null;
  deletedIncluded?: boolean;
};

export type MenuItemUpsertRequestDto = {
  name: string;
  unit: string;
  defaultAmountBeforeVatPerUnit: number;
  defaultVatPercentagePerUnit: number;
  /** @nullable */
  categoryId: number | null;
};

export type OrderBasicResponseDto = {
  id: number;
  itemAmount: number;
  isFinished: boolean;
};

export type OrderItemDetailResponseDto = {
  id: number;
  amountBeforeVatPerUnit: number;
  vatPercentagePerUnit: number;
  quantity: number;
  menuItem: MenuItemBasicResponseDto;
};

export type SeatingBasicResponseDto = {
  id: number;
  name: string;
  activeOrder: OrderBasicResponseDto | null;
  isDeleted: boolean;
};

export type OrderDetailResponseDto = {
  id: number;
  createdDateTime: string;
  lastUpdatedDateTime: string | null;
  finishedDateTime: string | null;
  itemAmount: number;
  items: OrderItemDetailResponseDto[];
  createdUser: UserBasicResponseDto;
  lastUpdatedUser: UserBasicResponseDto | null;
  finishedUser: UserBasicResponseDto | null;
  seating: SeatingBasicResponseDto;
};

export type OrderItemUpsertRequestDto = {
  /** @nullable */
  id: number | null;
  amountBeforeVatPerUnit: number;
  vatPercentagePerUnit: number;
  quantity: number;
  menuItemId: number;
};

export type OrderListSortingCriterion = number;

export type OrderListRequestDto = {
  sortByAscending?: boolean;
  sortByCriterion?: OrderListSortingCriterion;
  page?: number;
  resultsPerPage?: number;
  deletedIncluded?: boolean;
};

export type OrderListResponseDto = {
  items: OrderBasicResponseDto[];
  pageCount: number;
  itemCount: number;
};

export type OrderUpsertRequestDto = {
  seatingId: number;
  items: OrderItemUpsertRequestDto[];
};

export type ProblemDetails = {
  /** @nullable */
  type?: string | null;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  status?: number | null;
  /** @nullable */
  detail?: string | null;
  /** @nullable */
  instance?: string | null;
};

export type SeatingDetailResponseDto = {
  id: number;
  name: string;
  activeOrder: OrderBasicResponseDto | null;
};

export type SeatingUpsertRequestDto = {
  name: string;
};

export type UserCreateRequestDto = {
  userName: string;
  password: string;
};

export type UserDetailResponseDto = {
  id: number;
  userName: string;
  deletedDateTime: string | null;
};

export type VerifyCredentialsRequestDto = {
  userName: string;
  password: string;
};
