/**
 * Generated by orval 🍺
 * Do not edit manually.
 * HCManagement | v1
 * OpenAPI spec version: 1.0.0
 */
import type { SeatingBasicResponseDto, SeatingDetailResponseDto, SeatingUpsertRequestDto } from "./schema.schemas";

import { fetchAndThrowAsync } from "../mutators/fetch";

export const getGetAllAsyncUrl = () => {
  return `/api/seatings`;
};

export const getAllAsync = async (
  options?: Parameters<typeof fetchAndThrowAsync>[1],
): Promise<SeatingBasicResponseDto[]> => {
  return fetchAndThrowAsync<SeatingBasicResponseDto[]>(getGetAllAsyncUrl(), {
    ...options,
    method: "GET",
  });
};

export const getCreateAsyncUrl = () => {
  return `/api/seatings`;
};

export const createAsync = async (
  seatingUpsertRequestDto: SeatingUpsertRequestDto,
  options?: Parameters<typeof fetchAndThrowAsync>[1],
): Promise<number> => {
  const getHeaders = (h?: NonNullable<RequestInit["headers"]>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
  return fetchAndThrowAsync<number>(getCreateAsyncUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...getHeaders(options?.headers) },
    body: JSON.stringify(seatingUpsertRequestDto),
  });
};

export const getGetDetailAsyncUrl = (id: number) => {
  return `/api/seatings/${id}`;
};

export const getDetailAsync = async (
  id: number,
  options?: Parameters<typeof fetchAndThrowAsync>[1],
): Promise<SeatingDetailResponseDto> => {
  return fetchAndThrowAsync<SeatingDetailResponseDto>(getGetDetailAsyncUrl(id), {
    ...options,
    method: "GET",
  });
};

export const getUpdateAsyncUrl = (id: number) => {
  return `/api/seatings/${id}`;
};

export const updateAsync = async (
  id: number,
  seatingUpsertRequestDto: SeatingUpsertRequestDto,
  options?: Parameters<typeof fetchAndThrowAsync>[1],
): Promise<void> => {
  const getHeaders = (h?: NonNullable<RequestInit["headers"]>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
  return fetchAndThrowAsync<void>(getUpdateAsyncUrl(id), {
    ...options,
    method: "PUT",
    headers: { "Content-Type": "application/json", ...getHeaders(options?.headers) },
    body: JSON.stringify(seatingUpsertRequestDto),
  });
};

export const getDeleteAsyncUrl = (id: number) => {
  return `/api/seatings/${id}`;
};

export const deleteAsync = async (id: number, options?: Parameters<typeof fetchAndThrowAsync>[1]): Promise<void> => {
  return fetchAndThrowAsync<void>(getDeleteAsyncUrl(id), {
    ...options,
    method: "DELETE",
  });
};
