/**
 * Generated by orval 🍺
 * Do not edit manually.
 * HCManagement | v1
 * OpenAPI spec version: 1.0.0
 */
import type { UserCreateRequestDto, UserDetailResponseDto } from "./schema.schemas";

import { fetchAndThrowAsync } from "../mutators/fetch";

export const getGetDetailByIdAsyncUrl = (id: number) => {
  return `/api/users/${id}`;
};

export const getDetailByIdAsync = async (
  id: number,
  options?: Parameters<typeof fetchAndThrowAsync>[1],
): Promise<UserDetailResponseDto> => {
  return fetchAndThrowAsync<UserDetailResponseDto>(getGetDetailByIdAsyncUrl(id), {
    ...options,
    method: "GET",
  });
};

export const getDeleteAsyncUrl = (id: number) => {
  return `/api/users/${id}`;
};

export const deleteAsync = async (id: number, options?: Parameters<typeof fetchAndThrowAsync>[1]): Promise<void> => {
  return fetchAndThrowAsync<void>(getDeleteAsyncUrl(id), {
    ...options,
    method: "DELETE",
  });
};

export const getCreateAsyncUrl = () => {
  return `/api/users`;
};

export const createAsync = async (
  userCreateRequestDto: UserCreateRequestDto,
  options?: Parameters<typeof fetchAndThrowAsync>[1],
): Promise<number> => {
  const getHeaders = (h?: NonNullable<RequestInit["headers"]>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
  return fetchAndThrowAsync<number>(getCreateAsyncUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...getHeaders(options?.headers) },
    body: JSON.stringify(userCreateRequestDto),
  });
};
