// This file is auto-generated by @hey-api/openapi-ts

export const ChangePasswordRequestDtoSchema = {
  required: ["currentPassword", "newPassword"],
  type: "object",
  properties: {
    currentPassword: {
      type: "string",
    },
    newPassword: {
      type: "string",
    },
  },
} as const;

export const MenuCategoryBasicResponseDtoSchema = {
  required: ["id", "name"],
  type: "object",
  properties: {
    id: {
      type: "integer",
      format: "int32",
    },
    name: {
      type: ["null", "string"],
    },
  },
} as const;

export const MenuCategoryUpsertRequestDtoSchema = {
  required: ["name"],
  type: "object",
  properties: {
    name: {
      type: "string",
    },
    index: {
      type: ["null", "integer"],
      format: "int32",
    },
  },
} as const;

export const MenuItemBasicResponseDtoSchema = {
  required: ["id", "name", "unit", "defaultAmountBeforeVatPerUnit", "defaultVatPercentagePerUnit", "isDeleted"],
  type: "object",
  properties: {
    id: {
      type: "integer",
      format: "int32",
    },
    name: {
      type: ["null", "string"],
    },
    unit: {
      type: ["null", "string"],
    },
    defaultAmountBeforeVatPerUnit: {
      type: "integer",
      format: "int64",
    },
    defaultVatPercentagePerUnit: {
      type: "integer",
      format: "int32",
    },
    isDeleted: {
      type: "boolean",
    },
  },
} as const;

export const MenuItemDetailResponseDtoSchema = {
  required: [
    "id",
    "name",
    "unit",
    "defaultAmountBeforeVatPerUnit",
    "defaultVatPercentagePerUnit",
    "createdUser",
    "createdDateTime",
    "lastUpdatedUser",
    "lastUpdatedDateTime",
    "deletedUser",
    "deletedDateTime",
  ],
  type: "object",
  properties: {
    id: {
      type: "integer",
      format: "int32",
    },
    name: {
      type: ["null", "string"],
    },
    unit: {
      type: ["null", "string"],
    },
    defaultAmountBeforeVatPerUnit: {
      type: "integer",
      format: "int64",
    },
    defaultVatPercentagePerUnit: {
      type: "integer",
      format: "int32",
    },
    createdUser: {
      $ref: "#/components/schemas/UserBasicResponseDto",
    },
    createdDateTime: {
      type: "string",
      format: "date-time",
    },
    lastUpdatedUser: {
      required: ["id", "userName", "isDeleted"],
      anyOf: [
        {
          $ref: "#/components/schemas/UserBasicResponseDto",
        },
        {
          type: "null",
        },
      ],
    },
    lastUpdatedDateTime: {
      anyOf: [
        {
          type: ["null", "string"],
          format: "date-time",
        },
        {
          type: "null",
        },
      ],
    },
    deletedUser: {
      required: ["id", "userName", "isDeleted"],
      anyOf: [
        {
          $ref: "#/components/schemas/UserBasicResponseDto",
        },
        {
          type: "null",
        },
      ],
    },
    deletedDateTime: {
      anyOf: [
        {
          type: ["null", "string"],
          format: "date-time",
        },
        {
          type: "null",
        },
      ],
    },
  },
} as const;

export const MenuItemListRequestDtoSchema = {
  type: "object",
  properties: {
    sortByAscending: {
      type: "boolean",
    },
    sortByCriterion: {
      $ref: "#/components/schemas/MenuItemListSortingCriterion",
    },
    searchContent: {
      type: ["null", "string"],
    },
    categoryId: {
      type: ["null", "integer"],
      format: "int32",
    },
    deletedIncluded: {
      type: "boolean",
    },
  },
} as const;

export const MenuItemListSortingCriterionSchema = {
  type: "integer",
} as const;

export const MenuItemUpsertRequestDtoSchema = {
  required: ["name", "unit", "defaultAmountBeforeVatPerUnit", "defaultVatPercentagePerUnit", "categoryId"],
  type: "object",
  properties: {
    name: {
      type: "string",
    },
    unit: {
      type: "string",
    },
    defaultAmountBeforeVatPerUnit: {
      type: "integer",
      format: "int64",
    },
    defaultVatPercentagePerUnit: {
      type: "integer",
      format: "int32",
    },
    categoryId: {
      type: ["null", "integer"],
      format: "int32",
    },
  },
} as const;

export const OrderBasicResponseDtoSchema = {
  required: ["id", "itemAmount", "isFinished"],
  type: "object",
  properties: {
    id: {
      type: "integer",
      format: "int32",
    },
    itemAmount: {
      type: "integer",
      format: "int64",
    },
    isFinished: {
      type: "boolean",
    },
  },
} as const;

export const OrderDetailResponseDtoSchema = {
  required: [
    "id",
    "createdDateTime",
    "lastUpdatedDateTime",
    "finishedDateTime",
    "itemAmount",
    "items",
    "createdUser",
    "lastUpdatedUser",
    "finishedUser",
    "seating",
  ],
  type: "object",
  properties: {
    id: {
      type: "integer",
      format: "int32",
    },
    createdDateTime: {
      type: "string",
      format: "date-time",
    },
    lastUpdatedDateTime: {
      anyOf: [
        {
          type: ["null", "string"],
          format: "date-time",
        },
        {
          type: "null",
        },
      ],
    },
    finishedDateTime: {
      anyOf: [
        {
          type: ["null", "string"],
          format: "date-time",
        },
        {
          type: "null",
        },
      ],
    },
    itemAmount: {
      type: "integer",
      format: "int64",
    },
    items: {
      type: ["null", "array"],
      items: {
        $ref: "#/components/schemas/OrderItemDetailResponseDto",
      },
    },
    createdUser: {
      $ref: "#/components/schemas/UserBasicResponseDto",
    },
    lastUpdatedUser: {
      required: ["id", "userName", "isDeleted"],
      anyOf: [
        {
          $ref: "#/components/schemas/UserBasicResponseDto",
        },
        {
          type: "null",
        },
      ],
    },
    finishedUser: {
      required: ["id", "userName", "isDeleted"],
      anyOf: [
        {
          $ref: "#/components/schemas/UserBasicResponseDto",
        },
        {
          type: "null",
        },
      ],
    },
    seating: {
      $ref: "#/components/schemas/SeatingBasicResponseDto",
    },
  },
} as const;

export const OrderItemDetailResponseDtoSchema = {
  required: ["id", "amountBeforeVatPerUnit", "vatPercentagePerUnit", "quantity", "menuItem"],
  type: "object",
  properties: {
    id: {
      type: "integer",
      format: "int32",
    },
    amountBeforeVatPerUnit: {
      type: "integer",
      format: "int64",
    },
    vatPercentagePerUnit: {
      type: "integer",
      format: "int32",
    },
    quantity: {
      type: "integer",
      format: "int32",
    },
    menuItem: {
      $ref: "#/components/schemas/MenuItemBasicResponseDto",
    },
  },
} as const;

export const OrderItemUpsertRequestDtoSchema = {
  type: "object",
  properties: {
    id: {
      type: ["null", "integer"],
      format: "int32",
    },
    amountBeforeVatPerUnit: {
      type: "integer",
      format: "int64",
    },
    vatPercentagePerUnit: {
      type: "integer",
      format: "int32",
    },
    quantity: {
      type: "integer",
      format: "int32",
    },
    menuItemId: {
      type: "integer",
      format: "int32",
    },
  },
} as const;

export const OrderListRequestDtoSchema = {
  type: "object",
  properties: {
    sortByAscending: {
      type: "boolean",
    },
    sortByCriterion: {
      $ref: "#/components/schemas/OrderListSortingCriterion",
    },
    page: {
      type: "integer",
      format: "int32",
    },
    resultsPerPage: {
      type: "integer",
      format: "int32",
    },
    deletedIncluded: {
      type: "boolean",
    },
  },
} as const;

export const OrderListResponseDtoSchema = {
  required: ["items", "pageCount", "itemCount"],
  type: "object",
  properties: {
    items: {
      type: ["null", "array"],
      items: {
        $ref: "#/components/schemas/OrderBasicResponseDto",
      },
    },
    pageCount: {
      type: "integer",
      format: "int32",
    },
    itemCount: {
      type: "integer",
      format: "int32",
    },
  },
} as const;

export const OrderListSortingCriterionSchema = {
  type: "integer",
} as const;

export const OrderUpsertRequestDtoSchema = {
  type: "object",
  properties: {
    seatingId: {
      type: "integer",
      format: "int32",
    },
    items: {
      type: "array",
      items: {
        $ref: "#/components/schemas/OrderItemUpsertRequestDto",
      },
    },
  },
} as const;

export const ProblemDetailsSchema = {
  type: "object",
  properties: {
    type: {
      type: ["null", "string"],
    },
    title: {
      type: ["null", "string"],
    },
    status: {
      type: ["null", "integer"],
      format: "int32",
    },
    detail: {
      type: ["null", "string"],
    },
    instance: {
      type: ["null", "string"],
    },
  },
} as const;

export const SeatingBasicResponseDtoSchema = {
  required: ["id", "name", "activeOrder", "isDeleted"],
  type: "object",
  properties: {
    id: {
      type: "integer",
      format: "int32",
    },
    name: {
      type: ["null", "string"],
    },
    activeOrder: {
      required: ["id", "itemAmount", "isFinished"],
      anyOf: [
        {
          $ref: "#/components/schemas/OrderBasicResponseDto",
        },
        {
          type: "null",
        },
      ],
    },
    isDeleted: {
      type: "boolean",
    },
  },
} as const;

export const SeatingDetailResponseDtoSchema = {
  required: ["id", "name", "activeOrder"],
  type: "object",
  properties: {
    id: {
      type: "integer",
      format: "int32",
    },
    name: {
      type: ["null", "string"],
    },
    activeOrder: {
      required: ["id", "itemAmount", "isFinished"],
      anyOf: [
        {
          $ref: "#/components/schemas/OrderBasicResponseDto",
        },
        {
          type: "null",
        },
      ],
    },
  },
} as const;

export const SeatingUpsertRequestDtoSchema = {
  required: ["name"],
  type: "object",
  properties: {
    name: {
      type: "string",
    },
  },
} as const;

export const UserBasicResponseDtoSchema = {
  required: ["id", "userName", "isDeleted"],
  type: "object",
  properties: {
    id: {
      type: "integer",
      format: "int32",
    },
    userName: {
      type: "string",
    },
    isDeleted: {
      type: "boolean",
    },
  },
} as const;

export const UserCreateRequestDtoSchema = {
  required: ["userName", "password"],
  type: "object",
  properties: {
    userName: {
      type: "string",
    },
    password: {
      type: "string",
    },
  },
} as const;

export const UserDetailResponseDtoSchema = {
  required: ["id", "userName", "deletedDateTime"],
  type: "object",
  properties: {
    id: {
      type: "integer",
      format: "int32",
    },
    userName: {
      type: "string",
    },
    deletedDateTime: {
      anyOf: [
        {
          type: ["null", "string"],
          format: "date-time",
        },
        {
          type: "null",
        },
      ],
    },
  },
} as const;

export const VerifyCredentialsRequestDtoSchema = {
  required: ["userName", "password"],
  type: "object",
  properties: {
    userName: {
      type: "string",
    },
    password: {
      type: "string",
    },
  },
} as const;
