// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from "./client";
import { client } from "./client.gen";
import {
  getApiMenuItemsByIdResponseTransformer,
  getApiOrdersByIdResponseTransformer,
  getApiSeatingsByIdResponseTransformer,
  getApiSeatingsResponseTransformer,
  getApiUsersByIdResponseTransformer,
  postApiMenuItemsListResponseTransformer,
  postApiOrdersListResponseTransformer,
  postApiOrdersResponseTransformer,
} from "./transformers.gen";
import type {
  DeleteApiMenuCategoriesByIdData,
  DeleteApiMenuCategoriesByIdErrors,
  DeleteApiMenuCategoriesByIdResponses,
  DeleteApiMenuItemsByIdData,
  DeleteApiMenuItemsByIdErrors,
  DeleteApiMenuItemsByIdResponses,
  DeleteApiOrdersByIdData,
  DeleteApiOrdersByIdErrors,
  DeleteApiOrdersByIdResponses,
  DeleteApiSeatingsByIdData,
  DeleteApiSeatingsByIdErrors,
  DeleteApiSeatingsByIdResponses,
  DeleteApiUsersByIdData,
  DeleteApiUsersByIdErrors,
  DeleteApiUsersByIdResponses,
  GetApiAuthenticationCallerDetailData,
  GetApiAuthenticationCallerDetailErrors,
  GetApiAuthenticationCallerDetailResponses,
  GetApiMenuCategoriesByIdData,
  GetApiMenuCategoriesByIdErrors,
  GetApiMenuCategoriesByIdResponses,
  GetApiMenuCategoriesData,
  GetApiMenuCategoriesErrors,
  GetApiMenuCategoriesResponses,
  GetApiMenuItemsByIdData,
  GetApiMenuItemsByIdErrors,
  GetApiMenuItemsByIdResponses,
  GetApiMenuItemsDefaultListParametersData,
  GetApiMenuItemsDefaultListParametersResponses,
  GetApiOrdersByIdData,
  GetApiOrdersByIdErrors,
  GetApiOrdersByIdResponses,
  GetApiOrdersDefaultListParametersData,
  GetApiOrdersDefaultListParametersResponses,
  GetApiSeatingsByIdData,
  GetApiSeatingsByIdErrors,
  GetApiSeatingsByIdResponses,
  GetApiSeatingsData,
  GetApiSeatingsErrors,
  GetApiSeatingsResponses,
  GetApiUsersByIdData,
  GetApiUsersByIdErrors,
  GetApiUsersByIdResponses,
  PostApiAuthenticationCheckAuthenticationStatusData,
  PostApiAuthenticationCheckAuthenticationStatusErrors,
  PostApiAuthenticationCheckAuthenticationStatusResponses,
  PostApiAuthenticationClearAccessCookieData,
  PostApiAuthenticationClearAccessCookieErrors,
  PostApiAuthenticationClearAccessCookieResponses,
  PostApiAuthenticationGetAccessCookieData,
  PostApiAuthenticationGetAccessCookieErrors,
  PostApiAuthenticationGetAccessCookieResponses,
  PostApiMenuCategoriesData,
  PostApiMenuCategoriesErrors,
  PostApiMenuCategoriesResponses,
  PostApiMenuItemsData,
  PostApiMenuItemsErrors,
  PostApiMenuItemsListData,
  PostApiMenuItemsListErrors,
  PostApiMenuItemsListResponses,
  PostApiMenuItemsResponses,
  PostApiOrdersData,
  PostApiOrdersErrors,
  PostApiOrdersListData,
  PostApiOrdersListErrors,
  PostApiOrdersListResponses,
  PostApiOrdersResponses,
  PostApiSeatingsData,
  PostApiSeatingsErrors,
  PostApiSeatingsResponses,
  PostApiUsersData,
  PostApiUsersErrors,
  PostApiUsersResponses,
  PutApiAuthenticationChangePasswordData,
  PutApiAuthenticationChangePasswordErrors,
  PutApiAuthenticationChangePasswordResponses,
  PutApiMenuCategoriesByIdData,
  PutApiMenuCategoriesByIdErrors,
  PutApiMenuCategoriesByIdResponses,
  PutApiMenuItemsByIdData,
  PutApiMenuItemsByIdErrors,
  PutApiMenuItemsByIdResponses,
  PutApiOrdersByIdData,
  PutApiOrdersByIdErrors,
  PutApiOrdersByIdResponses,
  PutApiSeatingsByIdData,
  PutApiSeatingsByIdErrors,
  PutApiSeatingsByIdResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

export class Authentication {
  public static getAccessCookieAsync<ThrowOnError extends boolean = false>(
    options: Options<PostApiAuthenticationGetAccessCookieData, ThrowOnError>,
  ): RequestResult<
    PostApiAuthenticationGetAccessCookieResponses,
    PostApiAuthenticationGetAccessCookieErrors,
    ThrowOnError
  > {
    return (options.client ?? client).post<
      PostApiAuthenticationGetAccessCookieResponses,
      PostApiAuthenticationGetAccessCookieErrors,
      ThrowOnError
    >({
      url: "/api/authentication/get-access-cookie",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  public static clearAccessCookieAsync<ThrowOnError extends boolean = false>(
    options?: Options<PostApiAuthenticationClearAccessCookieData, ThrowOnError>,
  ): RequestResult<
    PostApiAuthenticationClearAccessCookieResponses,
    PostApiAuthenticationClearAccessCookieErrors,
    ThrowOnError
  > {
    return (options?.client ?? client).post<
      PostApiAuthenticationClearAccessCookieResponses,
      PostApiAuthenticationClearAccessCookieErrors,
      ThrowOnError
    >({ url: "/api/authentication/clear-access-cookie", ...options });
  }

  public static callerDetailAsync<ThrowOnError extends boolean = false>(
    options?: Options<GetApiAuthenticationCallerDetailData, ThrowOnError>,
  ): RequestResult<GetApiAuthenticationCallerDetailResponses, GetApiAuthenticationCallerDetailErrors, ThrowOnError> {
    return (options?.client ?? client).get<
      GetApiAuthenticationCallerDetailResponses,
      GetApiAuthenticationCallerDetailErrors,
      ThrowOnError
    >({ url: "/api/authentication/caller-detail", ...options });
  }

  public static changePasswordAsync<ThrowOnError extends boolean = false>(
    options: Options<PutApiAuthenticationChangePasswordData, ThrowOnError>,
  ): RequestResult<
    PutApiAuthenticationChangePasswordResponses,
    PutApiAuthenticationChangePasswordErrors,
    ThrowOnError
  > {
    return (options.client ?? client).put<
      PutApiAuthenticationChangePasswordResponses,
      PutApiAuthenticationChangePasswordErrors,
      ThrowOnError
    >({
      url: "/api/authentication/change-password",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  public static checkAuthenticationStatusAsync<ThrowOnError extends boolean = false>(
    options?: Options<PostApiAuthenticationCheckAuthenticationStatusData, ThrowOnError>,
  ): RequestResult<
    PostApiAuthenticationCheckAuthenticationStatusResponses,
    PostApiAuthenticationCheckAuthenticationStatusErrors,
    ThrowOnError
  > {
    return (options?.client ?? client).post<
      PostApiAuthenticationCheckAuthenticationStatusResponses,
      PostApiAuthenticationCheckAuthenticationStatusErrors,
      ThrowOnError
    >({ url: "/api/authentication/check-authentication-status", ...options });
  }
}

export class Authentication2 {
  static authentication = Authentication;
}

export class MenuCategory {
  public static getAllAsync<ThrowOnError extends boolean = false>(
    options?: Options<GetApiMenuCategoriesData, ThrowOnError>,
  ): RequestResult<GetApiMenuCategoriesResponses, GetApiMenuCategoriesErrors, ThrowOnError> {
    return (options?.client ?? client).get<GetApiMenuCategoriesResponses, GetApiMenuCategoriesErrors, ThrowOnError>({
      url: "/api/menu-categories",
      ...options,
    });
  }

  public static createAsync<ThrowOnError extends boolean = false>(
    options: Options<PostApiMenuCategoriesData, ThrowOnError>,
  ): RequestResult<PostApiMenuCategoriesResponses, PostApiMenuCategoriesErrors, ThrowOnError> {
    return (options.client ?? client).post<PostApiMenuCategoriesResponses, PostApiMenuCategoriesErrors, ThrowOnError>({
      url: "/api/menu-categories",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  public static deleteAsync<ThrowOnError extends boolean = false>(
    options: Options<DeleteApiMenuCategoriesByIdData, ThrowOnError>,
  ): RequestResult<DeleteApiMenuCategoriesByIdResponses, DeleteApiMenuCategoriesByIdErrors, ThrowOnError> {
    return (options.client ?? client).delete<
      DeleteApiMenuCategoriesByIdResponses,
      DeleteApiMenuCategoriesByIdErrors,
      ThrowOnError
    >({ url: "/api/menu-categories/{id}", ...options });
  }

  public static getSingleAsync<ThrowOnError extends boolean = false>(
    options: Options<GetApiMenuCategoriesByIdData, ThrowOnError>,
  ): RequestResult<GetApiMenuCategoriesByIdResponses, GetApiMenuCategoriesByIdErrors, ThrowOnError> {
    return (options.client ?? client).get<
      GetApiMenuCategoriesByIdResponses,
      GetApiMenuCategoriesByIdErrors,
      ThrowOnError
    >({ url: "/api/menu-categories/{id}", ...options });
  }

  public static updateAsync<ThrowOnError extends boolean = false>(
    options: Options<PutApiMenuCategoriesByIdData, ThrowOnError>,
  ): RequestResult<PutApiMenuCategoriesByIdResponses, PutApiMenuCategoriesByIdErrors, ThrowOnError> {
    return (options.client ?? client).put<
      PutApiMenuCategoriesByIdResponses,
      PutApiMenuCategoriesByIdErrors,
      ThrowOnError
    >({
      url: "/api/menu-categories/{id}",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }
}

export class MenuCategory2 {
  static menuCategory = MenuCategory;
}

export class MenuItem {
  public static getListAsync<ThrowOnError extends boolean = false>(
    options: Options<PostApiMenuItemsListData, ThrowOnError>,
  ): RequestResult<PostApiMenuItemsListResponses, PostApiMenuItemsListErrors, ThrowOnError> {
    return (options.client ?? client).post<PostApiMenuItemsListResponses, PostApiMenuItemsListErrors, ThrowOnError>({
      responseTransformer: postApiMenuItemsListResponseTransformer,
      url: "/api/menu-items/list",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  public static deleteAsync<ThrowOnError extends boolean = false>(
    options: Options<DeleteApiMenuItemsByIdData, ThrowOnError>,
  ): RequestResult<DeleteApiMenuItemsByIdResponses, DeleteApiMenuItemsByIdErrors, ThrowOnError> {
    return (options.client ?? client).delete<
      DeleteApiMenuItemsByIdResponses,
      DeleteApiMenuItemsByIdErrors,
      ThrowOnError
    >({ url: "/api/menu-items/{id}", ...options });
  }

  public static getDetailAsync<ThrowOnError extends boolean = false>(
    options: Options<GetApiMenuItemsByIdData, ThrowOnError>,
  ): RequestResult<GetApiMenuItemsByIdResponses, GetApiMenuItemsByIdErrors, ThrowOnError> {
    return (options.client ?? client).get<GetApiMenuItemsByIdResponses, GetApiMenuItemsByIdErrors, ThrowOnError>({
      responseTransformer: getApiMenuItemsByIdResponseTransformer,
      url: "/api/menu-items/{id}",
      ...options,
    });
  }

  public static updateAsync<ThrowOnError extends boolean = false>(
    options: Options<PutApiMenuItemsByIdData, ThrowOnError>,
  ): RequestResult<PutApiMenuItemsByIdResponses, PutApiMenuItemsByIdErrors, ThrowOnError> {
    return (options.client ?? client).put<PutApiMenuItemsByIdResponses, PutApiMenuItemsByIdErrors, ThrowOnError>({
      url: "/api/menu-items/{id}",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  public static createAsync<ThrowOnError extends boolean = false>(
    options: Options<PostApiMenuItemsData, ThrowOnError>,
  ): RequestResult<PostApiMenuItemsResponses, PostApiMenuItemsErrors, ThrowOnError> {
    return (options.client ?? client).post<PostApiMenuItemsResponses, PostApiMenuItemsErrors, ThrowOnError>({
      url: "/api/menu-items",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  public static getDefaultListParamtersAsync<ThrowOnError extends boolean = false>(
    options?: Options<GetApiMenuItemsDefaultListParametersData, ThrowOnError>,
  ): RequestResult<GetApiMenuItemsDefaultListParametersResponses, unknown, ThrowOnError> {
    return (options?.client ?? client).get<GetApiMenuItemsDefaultListParametersResponses, unknown, ThrowOnError>({
      url: "/api/menu-items/default-list-parameters",
      ...options,
    });
  }
}

export class MenuItem2 {
  static menuItem = MenuItem;
}

export class Order {
  public static getListAsync<ThrowOnError extends boolean = false>(
    options: Options<PostApiOrdersListData, ThrowOnError>,
  ): RequestResult<PostApiOrdersListResponses, PostApiOrdersListErrors, ThrowOnError> {
    return (options.client ?? client).post<PostApiOrdersListResponses, PostApiOrdersListErrors, ThrowOnError>({
      responseTransformer: postApiOrdersListResponseTransformer,
      url: "/api/orders/list",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  public static deleteAsync<ThrowOnError extends boolean = false>(
    options: Options<DeleteApiOrdersByIdData, ThrowOnError>,
  ): RequestResult<DeleteApiOrdersByIdResponses, DeleteApiOrdersByIdErrors, ThrowOnError> {
    return (options.client ?? client).delete<DeleteApiOrdersByIdResponses, DeleteApiOrdersByIdErrors, ThrowOnError>({
      url: "/api/orders/{id}",
      ...options,
    });
  }

  public static getDetailAsync<ThrowOnError extends boolean = false>(
    options: Options<GetApiOrdersByIdData, ThrowOnError>,
  ): RequestResult<GetApiOrdersByIdResponses, GetApiOrdersByIdErrors, ThrowOnError> {
    return (options.client ?? client).get<GetApiOrdersByIdResponses, GetApiOrdersByIdErrors, ThrowOnError>({
      responseTransformer: getApiOrdersByIdResponseTransformer,
      url: "/api/orders/{id}",
      ...options,
    });
  }

  public static finishAsync<ThrowOnError extends boolean = false>(
    options: Options<PutApiOrdersByIdData, ThrowOnError>,
  ): RequestResult<PutApiOrdersByIdResponses, PutApiOrdersByIdErrors, ThrowOnError> {
    return (options.client ?? client).put<PutApiOrdersByIdResponses, PutApiOrdersByIdErrors, ThrowOnError>({
      url: "/api/orders/{id}",
      ...options,
    });
  }

  public static createAsync<ThrowOnError extends boolean = false>(
    options: Options<PostApiOrdersData, ThrowOnError>,
  ): RequestResult<PostApiOrdersResponses, PostApiOrdersErrors, ThrowOnError> {
    return (options.client ?? client).post<PostApiOrdersResponses, PostApiOrdersErrors, ThrowOnError>({
      responseTransformer: postApiOrdersResponseTransformer,
      url: "/api/orders",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  public static getDefaultListParamtersAsync<ThrowOnError extends boolean = false>(
    options?: Options<GetApiOrdersDefaultListParametersData, ThrowOnError>,
  ): RequestResult<GetApiOrdersDefaultListParametersResponses, unknown, ThrowOnError> {
    return (options?.client ?? client).get<GetApiOrdersDefaultListParametersResponses, unknown, ThrowOnError>({
      url: "/api/orders/default-list-parameters",
      ...options,
    });
  }
}

export class Order2 {
  static order = Order;
}

export class Seating {
  public static getAllAsync<ThrowOnError extends boolean = false>(
    options?: Options<GetApiSeatingsData, ThrowOnError>,
  ): RequestResult<GetApiSeatingsResponses, GetApiSeatingsErrors, ThrowOnError> {
    return (options?.client ?? client).get<GetApiSeatingsResponses, GetApiSeatingsErrors, ThrowOnError>({
      responseTransformer: getApiSeatingsResponseTransformer,
      url: "/api/seatings",
      ...options,
    });
  }

  public static createAsync<ThrowOnError extends boolean = false>(
    options: Options<PostApiSeatingsData, ThrowOnError>,
  ): RequestResult<PostApiSeatingsResponses, PostApiSeatingsErrors, ThrowOnError> {
    return (options.client ?? client).post<PostApiSeatingsResponses, PostApiSeatingsErrors, ThrowOnError>({
      url: "/api/seatings",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  public static deleteAsync<ThrowOnError extends boolean = false>(
    options: Options<DeleteApiSeatingsByIdData, ThrowOnError>,
  ): RequestResult<DeleteApiSeatingsByIdResponses, DeleteApiSeatingsByIdErrors, ThrowOnError> {
    return (options.client ?? client).delete<DeleteApiSeatingsByIdResponses, DeleteApiSeatingsByIdErrors, ThrowOnError>(
      { url: "/api/seatings/{id}", ...options },
    );
  }

  public static getDetailAsync<ThrowOnError extends boolean = false>(
    options: Options<GetApiSeatingsByIdData, ThrowOnError>,
  ): RequestResult<GetApiSeatingsByIdResponses, GetApiSeatingsByIdErrors, ThrowOnError> {
    return (options.client ?? client).get<GetApiSeatingsByIdResponses, GetApiSeatingsByIdErrors, ThrowOnError>({
      responseTransformer: getApiSeatingsByIdResponseTransformer,
      url: "/api/seatings/{id}",
      ...options,
    });
  }

  public static updateAsync<ThrowOnError extends boolean = false>(
    options: Options<PutApiSeatingsByIdData, ThrowOnError>,
  ): RequestResult<PutApiSeatingsByIdResponses, PutApiSeatingsByIdErrors, ThrowOnError> {
    return (options.client ?? client).put<PutApiSeatingsByIdResponses, PutApiSeatingsByIdErrors, ThrowOnError>({
      url: "/api/seatings/{id}",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }
}

export class Seating2 {
  static seating = Seating;
}

export class User {
  public static deleteAsync<ThrowOnError extends boolean = false>(
    options: Options<DeleteApiUsersByIdData, ThrowOnError>,
  ): RequestResult<DeleteApiUsersByIdResponses, DeleteApiUsersByIdErrors, ThrowOnError> {
    return (options.client ?? client).delete<DeleteApiUsersByIdResponses, DeleteApiUsersByIdErrors, ThrowOnError>({
      url: "/api/users/{id}",
      ...options,
    });
  }

  public static getDetailByIdAsync<ThrowOnError extends boolean = false>(
    options: Options<GetApiUsersByIdData, ThrowOnError>,
  ): RequestResult<GetApiUsersByIdResponses, GetApiUsersByIdErrors, ThrowOnError> {
    return (options.client ?? client).get<GetApiUsersByIdResponses, GetApiUsersByIdErrors, ThrowOnError>({
      responseTransformer: getApiUsersByIdResponseTransformer,
      url: "/api/users/{id}",
      ...options,
    });
  }

  public static createAsync<ThrowOnError extends boolean = false>(
    options: Options<PostApiUsersData, ThrowOnError>,
  ): RequestResult<PostApiUsersResponses, PostApiUsersErrors, ThrowOnError> {
    return (options.client ?? client).post<PostApiUsersResponses, PostApiUsersErrors, ThrowOnError>({
      url: "/api/users",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }
}

export class User2 {
  static user = User;
}
