// This file is auto-generated by @hey-api/openapi-ts

import type {
  GetApiMenuItemsByIdResponse,
  GetApiOrdersByIdResponse,
  GetApiSeatingsByIdResponse,
  GetApiSeatingsResponse,
  GetApiUsersByIdResponse,
  PostApiMenuItemsListResponse,
  PostApiOrdersListResponse,
  PostApiOrdersResponse,
} from "./types.gen";

const menuItemBasicResponseDtoSchemaResponseTransformer = (data: any) => {
  data.defaultAmountBeforeVatPerUnit = BigInt(data.defaultAmountBeforeVatPerUnit.toString());
  return data;
};

export const postApiMenuItemsListResponseTransformer = async (data: any): Promise<PostApiMenuItemsListResponse> => {
  data = data.map((item: any) => menuItemBasicResponseDtoSchemaResponseTransformer(item));
  return data;
};

const menuItemDetailResponseDtoSchemaResponseTransformer = (data: any) => {
  data.defaultAmountBeforeVatPerUnit = BigInt(data.defaultAmountBeforeVatPerUnit.toString());
  data.createdDateTime = new Date(data.createdDateTime);
  if (data.lastUpdatedDateTime) {
    data.lastUpdatedDateTime = new Date(data.lastUpdatedDateTime);
  }
  if (data.deletedDateTime) {
    data.deletedDateTime = new Date(data.deletedDateTime);
  }
  return data;
};

export const getApiMenuItemsByIdResponseTransformer = async (data: any): Promise<GetApiMenuItemsByIdResponse> => {
  data = menuItemDetailResponseDtoSchemaResponseTransformer(data);
  return data;
};

const orderBasicResponseDtoSchemaResponseTransformer = (data: any) => {
  data.itemAmount = BigInt(data.itemAmount.toString());
  return data;
};

const orderListResponseDtoSchemaResponseTransformer = (data: any) => {
  if (data.items) {
    data.items = data.items.map((item: any) => orderBasicResponseDtoSchemaResponseTransformer(item));
  }
  return data;
};

export const postApiOrdersListResponseTransformer = async (data: any): Promise<PostApiOrdersListResponse> => {
  data = orderListResponseDtoSchemaResponseTransformer(data);
  return data;
};

const orderItemDetailResponseDtoSchemaResponseTransformer = (data: any) => {
  data.amountBeforeVatPerUnit = BigInt(data.amountBeforeVatPerUnit.toString());
  data.menuItem = menuItemBasicResponseDtoSchemaResponseTransformer(data.menuItem);
  return data;
};

const seatingBasicResponseDtoSchemaResponseTransformer = (data: any) => {
  if (data.activeOrder) {
    data.activeOrder = orderBasicResponseDtoSchemaResponseTransformer(data.activeOrder);
  }
  return data;
};

const orderDetailResponseDtoSchemaResponseTransformer = (data: any) => {
  data.createdDateTime = new Date(data.createdDateTime);
  if (data.lastUpdatedDateTime) {
    data.lastUpdatedDateTime = new Date(data.lastUpdatedDateTime);
  }
  if (data.finishedDateTime) {
    data.finishedDateTime = new Date(data.finishedDateTime);
  }
  data.itemAmount = BigInt(data.itemAmount.toString());
  if (data.items) {
    data.items = data.items.map((item: any) => orderItemDetailResponseDtoSchemaResponseTransformer(item));
  }
  data.seating = seatingBasicResponseDtoSchemaResponseTransformer(data.seating);
  return data;
};

export const getApiOrdersByIdResponseTransformer = async (data: any): Promise<GetApiOrdersByIdResponse> => {
  data = orderDetailResponseDtoSchemaResponseTransformer(data);
  return data;
};

export const postApiOrdersResponseTransformer = async (data: any): Promise<PostApiOrdersResponse> => {
  data = orderDetailResponseDtoSchemaResponseTransformer(data);
  return data;
};

export const getApiSeatingsResponseTransformer = async (data: any): Promise<GetApiSeatingsResponse> => {
  data = data.map((item: any) => seatingBasicResponseDtoSchemaResponseTransformer(item));
  return data;
};

const seatingDetailResponseDtoSchemaResponseTransformer = (data: any) => {
  if (data.activeOrder) {
    data.activeOrder = orderBasicResponseDtoSchemaResponseTransformer(data.activeOrder);
  }
  return data;
};

export const getApiSeatingsByIdResponseTransformer = async (data: any): Promise<GetApiSeatingsByIdResponse> => {
  data = seatingDetailResponseDtoSchemaResponseTransformer(data);
  return data;
};

const userDetailResponseDtoSchemaResponseTransformer = (data: any) => {
  if (data.deletedDateTime) {
    data.deletedDateTime = new Date(data.deletedDateTime);
  }
  return data;
};

export const getApiUsersByIdResponseTransformer = async (data: any): Promise<GetApiUsersByIdResponse> => {
  data = userDetailResponseDtoSchemaResponseTransformer(data);
  return data;
};
