// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: "http://localhost:5000/" | (string & {});
};

export type ChangePasswordRequestDto = {
  currentPassword: string;
  newPassword: string;
};

export type MenuCategoryBasicResponseDto = {
  id: number;
  name: null | string;
};

export type MenuCategoryUpsertRequestDto = {
  name: string;
  index?: null | number;
};

export type MenuItemBasicResponseDto = {
  id: number;
  name: null | string;
  unit: null | string;
  defaultAmountBeforeVatPerUnit: bigint;
  defaultVatPercentagePerUnit: number;
  isDeleted: boolean;
};

export type MenuItemDetailResponseDto = {
  id: number;
  name: null | string;
  unit: null | string;
  defaultAmountBeforeVatPerUnit: bigint;
  defaultVatPercentagePerUnit: number;
  createdUser: UserBasicResponseDto;
  createdDateTime: Date;
  lastUpdatedUser: UserBasicResponseDto | null;
  lastUpdatedDateTime: null | Date | null;
  deletedUser: UserBasicResponseDto | null;
  deletedDateTime: null | Date | null;
};

export type MenuItemListRequestDto = {
  sortByAscending?: boolean;
  sortByCriterion?: MenuItemListSortingCriterion;
  searchContent?: null | string;
  categoryId?: null | number;
  deletedIncluded?: boolean;
};

export type MenuItemListSortingCriterion = number;

export type MenuItemUpsertRequestDto = {
  name: string;
  unit: string;
  defaultAmountBeforeVatPerUnit: bigint;
  defaultVatPercentagePerUnit: number;
  categoryId: null | number;
};

export type OrderBasicResponseDto = {
  id: number;
  itemAmount: bigint;
  isFinished: boolean;
};

export type OrderDetailResponseDto = {
  id: number;
  createdDateTime: Date;
  lastUpdatedDateTime: null | Date | null;
  finishedDateTime: null | Date | null;
  itemAmount: bigint;
  items: null | Array<OrderItemDetailResponseDto>;
  createdUser: UserBasicResponseDto;
  lastUpdatedUser: UserBasicResponseDto | null;
  finishedUser: UserBasicResponseDto | null;
  seating: SeatingBasicResponseDto;
};

export type OrderItemDetailResponseDto = {
  id: number;
  amountBeforeVatPerUnit: bigint;
  vatPercentagePerUnit: number;
  quantity: number;
  menuItem: MenuItemBasicResponseDto;
};

export type OrderItemUpsertRequestDto = {
  id?: null | number;
  amountBeforeVatPerUnit?: bigint;
  vatPercentagePerUnit?: number;
  quantity?: number;
  menuItemId?: number;
};

export type OrderListRequestDto = {
  sortByAscending?: boolean;
  sortByCriterion?: OrderListSortingCriterion;
  page?: number;
  resultsPerPage?: number;
  deletedIncluded?: boolean;
};

export type OrderListResponseDto = {
  items: null | Array<OrderBasicResponseDto>;
  pageCount: number;
  itemCount: number;
};

export type OrderListSortingCriterion = number;

export type OrderUpsertRequestDto = {
  seatingId?: number;
  items?: Array<OrderItemUpsertRequestDto>;
};

export type ProblemDetails = {
  type?: null | string;
  title?: null | string;
  status?: null | number;
  detail?: null | string;
  instance?: null | string;
};

export type SeatingBasicResponseDto = {
  id: number;
  name: null | string;
  activeOrder: OrderBasicResponseDto | null;
  isDeleted: boolean;
};

export type SeatingDetailResponseDto = {
  id: number;
  name: null | string;
  activeOrder: OrderBasicResponseDto | null;
};

export type SeatingUpsertRequestDto = {
  name: string;
};

export type UserBasicResponseDto = {
  id: number;
  userName: string;
  isDeleted: boolean;
};

export type UserCreateRequestDto = {
  userName: string;
  password: string;
};

export type UserDetailResponseDto = {
  id: number;
  userName: string;
  deletedDateTime: null | Date | null;
};

export type VerifyCredentialsRequestDto = {
  userName: string;
  password: string;
};

export type PostApiAuthenticationGetAccessCookieData = {
  body: VerifyCredentialsRequestDto;
  path?: never;
  query?: never;
  url: "/api/authentication/get-access-cookie";
};

export type PostApiAuthenticationGetAccessCookieErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails;
  /**
   * Not Found
   */
  404: ProblemDetails;
  /**
   * Unprocessable Entity
   */
  422: ProblemDetails;
};

export type PostApiAuthenticationGetAccessCookieError =
  PostApiAuthenticationGetAccessCookieErrors[keyof PostApiAuthenticationGetAccessCookieErrors];

export type PostApiAuthenticationGetAccessCookieResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type PostApiAuthenticationClearAccessCookieData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/authentication/clear-access-cookie";
};

export type PostApiAuthenticationClearAccessCookieErrors = {
  /**
   * Unauthorized
   */
  401: ProblemDetails;
};

export type PostApiAuthenticationClearAccessCookieError =
  PostApiAuthenticationClearAccessCookieErrors[keyof PostApiAuthenticationClearAccessCookieErrors];

export type PostApiAuthenticationClearAccessCookieResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetApiAuthenticationCallerDetailData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/authentication/caller-detail";
};

export type GetApiAuthenticationCallerDetailErrors = {
  /**
   * Unauthorized
   */
  401: ProblemDetails;
};

export type GetApiAuthenticationCallerDetailError =
  GetApiAuthenticationCallerDetailErrors[keyof GetApiAuthenticationCallerDetailErrors];

export type GetApiAuthenticationCallerDetailResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type PutApiAuthenticationChangePasswordData = {
  body: ChangePasswordRequestDto;
  path?: never;
  query?: never;
  url: "/api/authentication/change-password";
};

export type PutApiAuthenticationChangePasswordErrors = {
  /**
   * Unauthorized
   */
  401: ProblemDetails;
  /**
   * Not Found
   */
  404: ProblemDetails;
  /**
   * Conflict
   */
  409: ProblemDetails;
  /**
   * Unprocessable Entity
   */
  422: ProblemDetails;
};

export type PutApiAuthenticationChangePasswordError =
  PutApiAuthenticationChangePasswordErrors[keyof PutApiAuthenticationChangePasswordErrors];

export type PutApiAuthenticationChangePasswordResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type PostApiAuthenticationCheckAuthenticationStatusData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/authentication/check-authentication-status";
};

export type PostApiAuthenticationCheckAuthenticationStatusErrors = {
  /**
   * Unauthorized
   */
  401: ProblemDetails;
};

export type PostApiAuthenticationCheckAuthenticationStatusError =
  PostApiAuthenticationCheckAuthenticationStatusErrors[keyof PostApiAuthenticationCheckAuthenticationStatusErrors];

export type PostApiAuthenticationCheckAuthenticationStatusResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetApiMenuCategoriesData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/menu-categories";
};

export type GetApiMenuCategoriesErrors = {
  /**
   * Unauthorized
   */
  401: ProblemDetails;
};

export type GetApiMenuCategoriesError = GetApiMenuCategoriesErrors[keyof GetApiMenuCategoriesErrors];

export type GetApiMenuCategoriesResponses = {
  /**
   * OK
   */
  200: Array<MenuCategoryBasicResponseDto>;
};

export type GetApiMenuCategoriesResponse = GetApiMenuCategoriesResponses[keyof GetApiMenuCategoriesResponses];

export type PostApiMenuCategoriesData = {
  body: MenuCategoryUpsertRequestDto;
  path?: never;
  query?: never;
  url: "/api/menu-categories";
};

export type PostApiMenuCategoriesErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails;
  /**
   * Unauthorized
   */
  401: ProblemDetails;
  /**
   * Conflict
   */
  409: ProblemDetails;
  /**
   * Unprocessable Entity
   */
  422: ProblemDetails;
};

export type PostApiMenuCategoriesError = PostApiMenuCategoriesErrors[keyof PostApiMenuCategoriesErrors];

export type PostApiMenuCategoriesResponses = {
  /**
   * Created
   */
  201: number;
};

export type PostApiMenuCategoriesResponse = PostApiMenuCategoriesResponses[keyof PostApiMenuCategoriesResponses];

export type DeleteApiMenuCategoriesByIdData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: "/api/menu-categories/{id}";
};

export type DeleteApiMenuCategoriesByIdErrors = {
  /**
   * Unauthorized
   */
  401: ProblemDetails;
  /**
   * Not Found
   */
  404: ProblemDetails;
  /**
   * Conflict
   */
  409: ProblemDetails;
  /**
   * Unprocessable Entity
   */
  422: ProblemDetails;
};

export type DeleteApiMenuCategoriesByIdError =
  DeleteApiMenuCategoriesByIdErrors[keyof DeleteApiMenuCategoriesByIdErrors];

export type DeleteApiMenuCategoriesByIdResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetApiMenuCategoriesByIdData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: "/api/menu-categories/{id}";
};

export type GetApiMenuCategoriesByIdErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails;
  /**
   * Unauthorized
   */
  401: ProblemDetails;
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type GetApiMenuCategoriesByIdError = GetApiMenuCategoriesByIdErrors[keyof GetApiMenuCategoriesByIdErrors];

export type GetApiMenuCategoriesByIdResponses = {
  /**
   * OK
   */
  200: MenuCategoryBasicResponseDto;
};

export type GetApiMenuCategoriesByIdResponse =
  GetApiMenuCategoriesByIdResponses[keyof GetApiMenuCategoriesByIdResponses];

export type PutApiMenuCategoriesByIdData = {
  body: MenuCategoryUpsertRequestDto;
  path: {
    id: number;
  };
  query?: never;
  url: "/api/menu-categories/{id}";
};

export type PutApiMenuCategoriesByIdErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails;
  /**
   * Unauthorized
   */
  401: ProblemDetails;
  /**
   * Conflict
   */
  409: ProblemDetails;
  /**
   * Unprocessable Entity
   */
  422: ProblemDetails;
};

export type PutApiMenuCategoriesByIdError = PutApiMenuCategoriesByIdErrors[keyof PutApiMenuCategoriesByIdErrors];

export type PutApiMenuCategoriesByIdResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type PostApiMenuItemsListData = {
  body: MenuItemListRequestDto;
  path?: never;
  query?: never;
  url: "/api/menu-items/list";
};

export type PostApiMenuItemsListErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails;
  /**
   * Unauthorized
   */
  401: ProblemDetails;
};

export type PostApiMenuItemsListError = PostApiMenuItemsListErrors[keyof PostApiMenuItemsListErrors];

export type PostApiMenuItemsListResponses = {
  /**
   * OK
   */
  200: Array<MenuItemBasicResponseDto>;
};

export type PostApiMenuItemsListResponse = PostApiMenuItemsListResponses[keyof PostApiMenuItemsListResponses];

export type DeleteApiMenuItemsByIdData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: "/api/menu-items/{id}";
};

export type DeleteApiMenuItemsByIdErrors = {
  /**
   * Unauthorized
   */
  401: ProblemDetails;
  /**
   * Not Found
   */
  404: ProblemDetails;
  /**
   * Conflict
   */
  409: ProblemDetails;
  /**
   * Unprocessable Entity
   */
  422: ProblemDetails;
};

export type DeleteApiMenuItemsByIdError = DeleteApiMenuItemsByIdErrors[keyof DeleteApiMenuItemsByIdErrors];

export type DeleteApiMenuItemsByIdResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetApiMenuItemsByIdData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: "/api/menu-items/{id}";
};

export type GetApiMenuItemsByIdErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails;
  /**
   * Unauthorized
   */
  401: ProblemDetails;
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type GetApiMenuItemsByIdError = GetApiMenuItemsByIdErrors[keyof GetApiMenuItemsByIdErrors];

export type GetApiMenuItemsByIdResponses = {
  /**
   * OK
   */
  200: MenuItemDetailResponseDto;
};

export type GetApiMenuItemsByIdResponse = GetApiMenuItemsByIdResponses[keyof GetApiMenuItemsByIdResponses];

export type PutApiMenuItemsByIdData = {
  body: MenuItemUpsertRequestDto;
  path: {
    id: number;
  };
  query?: never;
  url: "/api/menu-items/{id}";
};

export type PutApiMenuItemsByIdErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails;
  /**
   * Unauthorized
   */
  401: ProblemDetails;
  /**
   * Conflict
   */
  409: ProblemDetails;
  /**
   * Unprocessable Entity
   */
  422: ProblemDetails;
};

export type PutApiMenuItemsByIdError = PutApiMenuItemsByIdErrors[keyof PutApiMenuItemsByIdErrors];

export type PutApiMenuItemsByIdResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type PostApiMenuItemsData = {
  body: MenuItemUpsertRequestDto;
  path?: never;
  query?: never;
  url: "/api/menu-items";
};

export type PostApiMenuItemsErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails;
  /**
   * Unauthorized
   */
  401: ProblemDetails;
  /**
   * Conflict
   */
  409: ProblemDetails;
  /**
   * Unprocessable Entity
   */
  422: ProblemDetails;
};

export type PostApiMenuItemsError = PostApiMenuItemsErrors[keyof PostApiMenuItemsErrors];

export type PostApiMenuItemsResponses = {
  /**
   * Created
   */
  201: number;
};

export type PostApiMenuItemsResponse = PostApiMenuItemsResponses[keyof PostApiMenuItemsResponses];

export type GetApiMenuItemsDefaultListParametersData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/menu-items/default-list-parameters";
};

export type GetApiMenuItemsDefaultListParametersResponses = {
  /**
   * OK
   */
  200: MenuItemListRequestDto;
};

export type GetApiMenuItemsDefaultListParametersResponse =
  GetApiMenuItemsDefaultListParametersResponses[keyof GetApiMenuItemsDefaultListParametersResponses];

export type PostApiOrdersListData = {
  body: OrderListRequestDto;
  path?: never;
  query?: never;
  url: "/api/orders/list";
};

export type PostApiOrdersListErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails;
  /**
   * Unauthorized
   */
  401: ProblemDetails;
};

export type PostApiOrdersListError = PostApiOrdersListErrors[keyof PostApiOrdersListErrors];

export type PostApiOrdersListResponses = {
  /**
   * OK
   */
  200: OrderListResponseDto;
};

export type PostApiOrdersListResponse = PostApiOrdersListResponses[keyof PostApiOrdersListResponses];

export type DeleteApiOrdersByIdData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: "/api/orders/{id}";
};

export type DeleteApiOrdersByIdErrors = {
  /**
   * Unauthorized
   */
  401: ProblemDetails;
  /**
   * Not Found
   */
  404: ProblemDetails;
  /**
   * Conflict
   */
  409: ProblemDetails;
  /**
   * Unprocessable Entity
   */
  422: ProblemDetails;
};

export type DeleteApiOrdersByIdError = DeleteApiOrdersByIdErrors[keyof DeleteApiOrdersByIdErrors];

export type DeleteApiOrdersByIdResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetApiOrdersByIdData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: "/api/orders/{id}";
};

export type GetApiOrdersByIdErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails;
  /**
   * Unauthorized
   */
  401: ProblemDetails;
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type GetApiOrdersByIdError = GetApiOrdersByIdErrors[keyof GetApiOrdersByIdErrors];

export type GetApiOrdersByIdResponses = {
  /**
   * OK
   */
  200: OrderDetailResponseDto;
};

export type GetApiOrdersByIdResponse = GetApiOrdersByIdResponses[keyof GetApiOrdersByIdResponses];

export type PutApiOrdersByIdData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: "/api/orders/{id}";
};

export type PutApiOrdersByIdErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails;
  /**
   * Unauthorized
   */
  401: ProblemDetails;
  /**
   * Conflict
   */
  409: ProblemDetails;
  /**
   * Unprocessable Entity
   */
  422: ProblemDetails;
};

export type PutApiOrdersByIdError = PutApiOrdersByIdErrors[keyof PutApiOrdersByIdErrors];

export type PutApiOrdersByIdResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type PostApiOrdersData = {
  body: OrderUpsertRequestDto;
  path?: never;
  query?: never;
  url: "/api/orders";
};

export type PostApiOrdersErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails;
  /**
   * Unauthorized
   */
  401: ProblemDetails;
  /**
   * Conflict
   */
  409: ProblemDetails;
  /**
   * Unprocessable Entity
   */
  422: ProblemDetails;
};

export type PostApiOrdersError = PostApiOrdersErrors[keyof PostApiOrdersErrors];

export type PostApiOrdersResponses = {
  /**
   * Created
   */
  201: OrderDetailResponseDto;
};

export type PostApiOrdersResponse = PostApiOrdersResponses[keyof PostApiOrdersResponses];

export type GetApiOrdersDefaultListParametersData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/orders/default-list-parameters";
};

export type GetApiOrdersDefaultListParametersResponses = {
  /**
   * OK
   */
  200: OrderListRequestDto;
};

export type GetApiOrdersDefaultListParametersResponse =
  GetApiOrdersDefaultListParametersResponses[keyof GetApiOrdersDefaultListParametersResponses];

export type GetApiSeatingsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/seatings";
};

export type GetApiSeatingsErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails;
  /**
   * Unauthorized
   */
  401: ProblemDetails;
};

export type GetApiSeatingsError = GetApiSeatingsErrors[keyof GetApiSeatingsErrors];

export type GetApiSeatingsResponses = {
  /**
   * OK
   */
  200: Array<SeatingBasicResponseDto>;
};

export type GetApiSeatingsResponse = GetApiSeatingsResponses[keyof GetApiSeatingsResponses];

export type PostApiSeatingsData = {
  body: SeatingUpsertRequestDto;
  path?: never;
  query?: never;
  url: "/api/seatings";
};

export type PostApiSeatingsErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails;
  /**
   * Unauthorized
   */
  401: ProblemDetails;
  /**
   * Conflict
   */
  409: ProblemDetails;
  /**
   * Unprocessable Entity
   */
  422: ProblemDetails;
};

export type PostApiSeatingsError = PostApiSeatingsErrors[keyof PostApiSeatingsErrors];

export type PostApiSeatingsResponses = {
  /**
   * Created
   */
  201: number;
};

export type PostApiSeatingsResponse = PostApiSeatingsResponses[keyof PostApiSeatingsResponses];

export type DeleteApiSeatingsByIdData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: "/api/seatings/{id}";
};

export type DeleteApiSeatingsByIdErrors = {
  /**
   * Unauthorized
   */
  401: ProblemDetails;
  /**
   * Not Found
   */
  404: ProblemDetails;
  /**
   * Conflict
   */
  409: ProblemDetails;
  /**
   * Unprocessable Entity
   */
  422: ProblemDetails;
};

export type DeleteApiSeatingsByIdError = DeleteApiSeatingsByIdErrors[keyof DeleteApiSeatingsByIdErrors];

export type DeleteApiSeatingsByIdResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetApiSeatingsByIdData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: "/api/seatings/{id}";
};

export type GetApiSeatingsByIdErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails;
  /**
   * Unauthorized
   */
  401: ProblemDetails;
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type GetApiSeatingsByIdError = GetApiSeatingsByIdErrors[keyof GetApiSeatingsByIdErrors];

export type GetApiSeatingsByIdResponses = {
  /**
   * OK
   */
  200: SeatingDetailResponseDto;
};

export type GetApiSeatingsByIdResponse = GetApiSeatingsByIdResponses[keyof GetApiSeatingsByIdResponses];

export type PutApiSeatingsByIdData = {
  body: SeatingUpsertRequestDto;
  path: {
    id: number;
  };
  query?: never;
  url: "/api/seatings/{id}";
};

export type PutApiSeatingsByIdErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails;
  /**
   * Unauthorized
   */
  401: ProblemDetails;
  /**
   * Conflict
   */
  409: ProblemDetails;
  /**
   * Unprocessable Entity
   */
  422: ProblemDetails;
};

export type PutApiSeatingsByIdError = PutApiSeatingsByIdErrors[keyof PutApiSeatingsByIdErrors];

export type PutApiSeatingsByIdResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type DeleteApiUsersByIdData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: "/api/users/{id}";
};

export type DeleteApiUsersByIdErrors = {
  /**
   * Unauthorized
   */
  401: ProblemDetails;
  /**
   * Not Found
   */
  404: ProblemDetails;
  /**
   * Conflict
   */
  409: ProblemDetails;
  /**
   * Unprocessable Entity
   */
  422: ProblemDetails;
};

export type DeleteApiUsersByIdError = DeleteApiUsersByIdErrors[keyof DeleteApiUsersByIdErrors];

export type DeleteApiUsersByIdResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetApiUsersByIdData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: "/api/users/{id}";
};

export type GetApiUsersByIdErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails;
  /**
   * Unauthorized
   */
  401: ProblemDetails;
  /**
   * Not Found
   */
  404: ProblemDetails;
};

export type GetApiUsersByIdError = GetApiUsersByIdErrors[keyof GetApiUsersByIdErrors];

export type GetApiUsersByIdResponses = {
  /**
   * OK
   */
  200: UserDetailResponseDto;
};

export type GetApiUsersByIdResponse = GetApiUsersByIdResponses[keyof GetApiUsersByIdResponses];

export type PostApiUsersData = {
  body: UserCreateRequestDto;
  path?: never;
  query?: never;
  url: "/api/users";
};

export type PostApiUsersErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails;
  /**
   * Unauthorized
   */
  401: ProblemDetails;
  /**
   * Conflict
   */
  409: ProblemDetails;
  /**
   * Unprocessable Entity
   */
  422: ProblemDetails;
};

export type PostApiUsersError = PostApiUsersErrors[keyof PostApiUsersErrors];

export type PostApiUsersResponses = {
  /**
   * Created
   */
  201: number;
};

export type PostApiUsersResponse = PostApiUsersResponses[keyof PostApiUsersResponses];
