@host = http://127.0.0.1:5000
@basePath = {{host}}/api

# @name GetAccessCookie
// @no-log
POST {{host}}/api/authentication/get-access-cookie
Content-Type: application/json

{
    "userName": "admin",
    "password": "admin"
}

###
@accessCookie = {{GetAccessCookie.response.headers.set-cookie}}

###
# @name ClearAccessCookie
// @no-log
POST {{basePath}}/authentication/clear-access-cookie
Content-Type: application/json
Cookie: {{accessCookie}}

###
# @name ChangePassword
// @no-log
POST {{host}}/api/authentication/change-password
Content-Type: application/json
Cookie: {{accessCookie}}

{
    "newPassword": "admin47b1"
}

###
# @name UserDetail
GET {{basePath}}/users/1
Content-Type: application/json
Cookie: {{accessCookie}}

###
# @name MenuCategoryAll
GET {{basePath}}/menu-categories
Content-Type: application/json
Cookie: {{accessCookie}}

###
# @name MenuCategorySingle
GET {{basePath}}/menu-categories/8
Content-Type: application/json
Cookie: {{accessCookie}}

###
# @name MenuCategoryCreate
POST {{basePath}}/menu-categories
Content-Type: application/json
Cookie: {{accessCookie}}

{
    "name": "Test Category 2"
}

###
# @name MenuCategoryUpdate
PUT {{basePath}}/menu-categories/6
Content-Type: application/json
Cookie: {{accessCookie}}

{
    "name": "Test Category 1"
}

###
# @name MenuItemList
GET {{basePath}}/menu-items?categoryId=1
Content-Type: application/json
Cookie: {{accessCookie}}


###
# @name HealthCheck
GET {{host}}/health-check
Content-Type: application/json
Cookie: {{accessCookie}}
