
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Seating` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Seating
 * 
 */
export type SeatingModel = runtime.Types.Result.DefaultSelection<Prisma.$SeatingPayload>

export type AggregateSeating = {
  _count: SeatingCountAggregateOutputType | null
  _avg: SeatingAvgAggregateOutputType | null
  _sum: SeatingSumAggregateOutputType | null
  _min: SeatingMinAggregateOutputType | null
  _max: SeatingMaxAggregateOutputType | null
}

export type SeatingAvgAggregateOutputType = {
  id: number | null
}

export type SeatingSumAggregateOutputType = {
  id: number | null
}

export type SeatingMinAggregateOutputType = {
  id: number | null
  name: string | null
  isDeleted: boolean | null
  concurrencyVersion: string | null
}

export type SeatingMaxAggregateOutputType = {
  id: number | null
  name: string | null
  isDeleted: boolean | null
  concurrencyVersion: string | null
}

export type SeatingCountAggregateOutputType = {
  id: number
  name: number
  isDeleted: number
  concurrencyVersion: number
  _all: number
}


export type SeatingAvgAggregateInputType = {
  id?: true
}

export type SeatingSumAggregateInputType = {
  id?: true
}

export type SeatingMinAggregateInputType = {
  id?: true
  name?: true
  isDeleted?: true
  concurrencyVersion?: true
}

export type SeatingMaxAggregateInputType = {
  id?: true
  name?: true
  isDeleted?: true
  concurrencyVersion?: true
}

export type SeatingCountAggregateInputType = {
  id?: true
  name?: true
  isDeleted?: true
  concurrencyVersion?: true
  _all?: true
}

export type SeatingAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Seating to aggregate.
   */
  where?: Prisma.SeatingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Seatings to fetch.
   */
  orderBy?: Prisma.SeatingOrderByWithRelationInput | Prisma.SeatingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.SeatingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Seatings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Seatings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Seatings
  **/
  _count?: true | SeatingCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: SeatingAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: SeatingSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: SeatingMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: SeatingMaxAggregateInputType
}

export type GetSeatingAggregateType<T extends SeatingAggregateArgs> = {
      [P in keyof T & keyof AggregateSeating]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateSeating[P]>
    : Prisma.GetScalarType<T[P], AggregateSeating[P]>
}




export type SeatingGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SeatingWhereInput
  orderBy?: Prisma.SeatingOrderByWithAggregationInput | Prisma.SeatingOrderByWithAggregationInput[]
  by: Prisma.SeatingScalarFieldEnum[] | Prisma.SeatingScalarFieldEnum
  having?: Prisma.SeatingScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: SeatingCountAggregateInputType | true
  _avg?: SeatingAvgAggregateInputType
  _sum?: SeatingSumAggregateInputType
  _min?: SeatingMinAggregateInputType
  _max?: SeatingMaxAggregateInputType
}

export type SeatingGroupByOutputType = {
  id: number
  name: string
  isDeleted: boolean
  concurrencyVersion: string
  _count: SeatingCountAggregateOutputType | null
  _avg: SeatingAvgAggregateOutputType | null
  _sum: SeatingSumAggregateOutputType | null
  _min: SeatingMinAggregateOutputType | null
  _max: SeatingMaxAggregateOutputType | null
}

export type GetSeatingGroupByPayload<T extends SeatingGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<SeatingGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof SeatingGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], SeatingGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], SeatingGroupByOutputType[P]>
      }
    >
  >



export type SeatingWhereInput = {
  AND?: Prisma.SeatingWhereInput | Prisma.SeatingWhereInput[]
  OR?: Prisma.SeatingWhereInput[]
  NOT?: Prisma.SeatingWhereInput | Prisma.SeatingWhereInput[]
  id?: Prisma.IntFilter<"Seating"> | number
  name?: Prisma.StringFilter<"Seating"> | string
  isDeleted?: Prisma.BoolFilter<"Seating"> | boolean
  concurrencyVersion?: Prisma.StringFilter<"Seating"> | string
  orders?: Prisma.OrderListRelationFilter
}

export type SeatingOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  isDeleted?: Prisma.SortOrder
  concurrencyVersion?: Prisma.SortOrder
  orders?: Prisma.OrderOrderByRelationAggregateInput
}

export type SeatingWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  name?: string
  AND?: Prisma.SeatingWhereInput | Prisma.SeatingWhereInput[]
  OR?: Prisma.SeatingWhereInput[]
  NOT?: Prisma.SeatingWhereInput | Prisma.SeatingWhereInput[]
  isDeleted?: Prisma.BoolFilter<"Seating"> | boolean
  concurrencyVersion?: Prisma.StringFilter<"Seating"> | string
  orders?: Prisma.OrderListRelationFilter
}, "id" | "name">

export type SeatingOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  isDeleted?: Prisma.SortOrder
  concurrencyVersion?: Prisma.SortOrder
  _count?: Prisma.SeatingCountOrderByAggregateInput
  _avg?: Prisma.SeatingAvgOrderByAggregateInput
  _max?: Prisma.SeatingMaxOrderByAggregateInput
  _min?: Prisma.SeatingMinOrderByAggregateInput
  _sum?: Prisma.SeatingSumOrderByAggregateInput
}

export type SeatingScalarWhereWithAggregatesInput = {
  AND?: Prisma.SeatingScalarWhereWithAggregatesInput | Prisma.SeatingScalarWhereWithAggregatesInput[]
  OR?: Prisma.SeatingScalarWhereWithAggregatesInput[]
  NOT?: Prisma.SeatingScalarWhereWithAggregatesInput | Prisma.SeatingScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"Seating"> | number
  name?: Prisma.StringWithAggregatesFilter<"Seating"> | string
  isDeleted?: Prisma.BoolWithAggregatesFilter<"Seating"> | boolean
  concurrencyVersion?: Prisma.StringWithAggregatesFilter<"Seating"> | string
}

export type SeatingCreateInput = {
  name: string
  isDeleted?: boolean
  concurrencyVersion?: string
  orders?: Prisma.OrderCreateNestedManyWithoutSeatingInput
}

export type SeatingUncheckedCreateInput = {
  id?: number
  name: string
  isDeleted?: boolean
  concurrencyVersion?: string
  orders?: Prisma.OrderUncheckedCreateNestedManyWithoutSeatingInput
}

export type SeatingUpdateInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  isDeleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  concurrencyVersion?: Prisma.StringFieldUpdateOperationsInput | string
  orders?: Prisma.OrderUpdateManyWithoutSeatingNestedInput
}

export type SeatingUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  isDeleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  concurrencyVersion?: Prisma.StringFieldUpdateOperationsInput | string
  orders?: Prisma.OrderUncheckedUpdateManyWithoutSeatingNestedInput
}

export type SeatingCreateManyInput = {
  id?: number
  name: string
  isDeleted?: boolean
  concurrencyVersion?: string
}

export type SeatingUpdateManyMutationInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  isDeleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  concurrencyVersion?: Prisma.StringFieldUpdateOperationsInput | string
}

export type SeatingUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  isDeleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  concurrencyVersion?: Prisma.StringFieldUpdateOperationsInput | string
}

export type SeatingCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  isDeleted?: Prisma.SortOrder
  concurrencyVersion?: Prisma.SortOrder
}

export type SeatingAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type SeatingMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  isDeleted?: Prisma.SortOrder
  concurrencyVersion?: Prisma.SortOrder
}

export type SeatingMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  isDeleted?: Prisma.SortOrder
  concurrencyVersion?: Prisma.SortOrder
}

export type SeatingSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type SeatingScalarRelationFilter = {
  is?: Prisma.SeatingWhereInput
  isNot?: Prisma.SeatingWhereInput
}

export type SeatingCreateNestedOneWithoutOrdersInput = {
  create?: Prisma.XOR<Prisma.SeatingCreateWithoutOrdersInput, Prisma.SeatingUncheckedCreateWithoutOrdersInput>
  connectOrCreate?: Prisma.SeatingCreateOrConnectWithoutOrdersInput
  connect?: Prisma.SeatingWhereUniqueInput
}

export type SeatingUpdateOneRequiredWithoutOrdersNestedInput = {
  create?: Prisma.XOR<Prisma.SeatingCreateWithoutOrdersInput, Prisma.SeatingUncheckedCreateWithoutOrdersInput>
  connectOrCreate?: Prisma.SeatingCreateOrConnectWithoutOrdersInput
  upsert?: Prisma.SeatingUpsertWithoutOrdersInput
  connect?: Prisma.SeatingWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.SeatingUpdateToOneWithWhereWithoutOrdersInput, Prisma.SeatingUpdateWithoutOrdersInput>, Prisma.SeatingUncheckedUpdateWithoutOrdersInput>
}

export type SeatingCreateWithoutOrdersInput = {
  name: string
  isDeleted?: boolean
  concurrencyVersion?: string
}

export type SeatingUncheckedCreateWithoutOrdersInput = {
  id?: number
  name: string
  isDeleted?: boolean
  concurrencyVersion?: string
}

export type SeatingCreateOrConnectWithoutOrdersInput = {
  where: Prisma.SeatingWhereUniqueInput
  create: Prisma.XOR<Prisma.SeatingCreateWithoutOrdersInput, Prisma.SeatingUncheckedCreateWithoutOrdersInput>
}

export type SeatingUpsertWithoutOrdersInput = {
  update: Prisma.XOR<Prisma.SeatingUpdateWithoutOrdersInput, Prisma.SeatingUncheckedUpdateWithoutOrdersInput>
  create: Prisma.XOR<Prisma.SeatingCreateWithoutOrdersInput, Prisma.SeatingUncheckedCreateWithoutOrdersInput>
  where?: Prisma.SeatingWhereInput
}

export type SeatingUpdateToOneWithWhereWithoutOrdersInput = {
  where?: Prisma.SeatingWhereInput
  data: Prisma.XOR<Prisma.SeatingUpdateWithoutOrdersInput, Prisma.SeatingUncheckedUpdateWithoutOrdersInput>
}

export type SeatingUpdateWithoutOrdersInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  isDeleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  concurrencyVersion?: Prisma.StringFieldUpdateOperationsInput | string
}

export type SeatingUncheckedUpdateWithoutOrdersInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  isDeleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  concurrencyVersion?: Prisma.StringFieldUpdateOperationsInput | string
}


/**
 * Count Type SeatingCountOutputType
 */

export type SeatingCountOutputType = {
  orders: number
}

export type SeatingCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  orders?: boolean | SeatingCountOutputTypeCountOrdersArgs
}

/**
 * SeatingCountOutputType without action
 */
export type SeatingCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SeatingCountOutputType
   */
  select?: Prisma.SeatingCountOutputTypeSelect<ExtArgs> | null
}

/**
 * SeatingCountOutputType without action
 */
export type SeatingCountOutputTypeCountOrdersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.OrderWhereInput
}


export type SeatingSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  isDeleted?: boolean
  concurrencyVersion?: boolean
  orders?: boolean | Prisma.Seating$ordersArgs<ExtArgs>
  _count?: boolean | Prisma.SeatingCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["seating"]>

export type SeatingSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  isDeleted?: boolean
  concurrencyVersion?: boolean
}, ExtArgs["result"]["seating"]>

export type SeatingSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  isDeleted?: boolean
  concurrencyVersion?: boolean
}, ExtArgs["result"]["seating"]>

export type SeatingSelectScalar = {
  id?: boolean
  name?: boolean
  isDeleted?: boolean
  concurrencyVersion?: boolean
}

export type SeatingOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "isDeleted" | "concurrencyVersion", ExtArgs["result"]["seating"]>
export type SeatingInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  orders?: boolean | Prisma.Seating$ordersArgs<ExtArgs>
  _count?: boolean | Prisma.SeatingCountOutputTypeDefaultArgs<ExtArgs>
}
export type SeatingIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type SeatingIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $SeatingPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Seating"
  objects: {
    orders: Prisma.$OrderPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    name: string
    isDeleted: boolean
    concurrencyVersion: string
  }, ExtArgs["result"]["seating"]>
  composites: {}
}

export type SeatingGetPayload<S extends boolean | null | undefined | SeatingDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$SeatingPayload, S>

export type SeatingCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<SeatingFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: SeatingCountAggregateInputType | true
  }

export interface SeatingDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Seating'], meta: { name: 'Seating' } }
  /**
   * Find zero or one Seating that matches the filter.
   * @param {SeatingFindUniqueArgs} args - Arguments to find a Seating
   * @example
   * // Get one Seating
   * const seating = await prisma.seating.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends SeatingFindUniqueArgs>(args: Prisma.SelectSubset<T, SeatingFindUniqueArgs<ExtArgs>>): Prisma.Prisma__SeatingClient<runtime.Types.Result.GetResult<Prisma.$SeatingPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Seating that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {SeatingFindUniqueOrThrowArgs} args - Arguments to find a Seating
   * @example
   * // Get one Seating
   * const seating = await prisma.seating.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends SeatingFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, SeatingFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__SeatingClient<runtime.Types.Result.GetResult<Prisma.$SeatingPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Seating that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SeatingFindFirstArgs} args - Arguments to find a Seating
   * @example
   * // Get one Seating
   * const seating = await prisma.seating.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends SeatingFindFirstArgs>(args?: Prisma.SelectSubset<T, SeatingFindFirstArgs<ExtArgs>>): Prisma.Prisma__SeatingClient<runtime.Types.Result.GetResult<Prisma.$SeatingPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Seating that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SeatingFindFirstOrThrowArgs} args - Arguments to find a Seating
   * @example
   * // Get one Seating
   * const seating = await prisma.seating.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends SeatingFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, SeatingFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__SeatingClient<runtime.Types.Result.GetResult<Prisma.$SeatingPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Seatings that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SeatingFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Seatings
   * const seatings = await prisma.seating.findMany()
   * 
   * // Get first 10 Seatings
   * const seatings = await prisma.seating.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const seatingWithIdOnly = await prisma.seating.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends SeatingFindManyArgs>(args?: Prisma.SelectSubset<T, SeatingFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SeatingPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Seating.
   * @param {SeatingCreateArgs} args - Arguments to create a Seating.
   * @example
   * // Create one Seating
   * const Seating = await prisma.seating.create({
   *   data: {
   *     // ... data to create a Seating
   *   }
   * })
   * 
   */
  create<T extends SeatingCreateArgs>(args: Prisma.SelectSubset<T, SeatingCreateArgs<ExtArgs>>): Prisma.Prisma__SeatingClient<runtime.Types.Result.GetResult<Prisma.$SeatingPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Seatings.
   * @param {SeatingCreateManyArgs} args - Arguments to create many Seatings.
   * @example
   * // Create many Seatings
   * const seating = await prisma.seating.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends SeatingCreateManyArgs>(args?: Prisma.SelectSubset<T, SeatingCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Seatings and returns the data saved in the database.
   * @param {SeatingCreateManyAndReturnArgs} args - Arguments to create many Seatings.
   * @example
   * // Create many Seatings
   * const seating = await prisma.seating.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Seatings and only return the `id`
   * const seatingWithIdOnly = await prisma.seating.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends SeatingCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, SeatingCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SeatingPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Seating.
   * @param {SeatingDeleteArgs} args - Arguments to delete one Seating.
   * @example
   * // Delete one Seating
   * const Seating = await prisma.seating.delete({
   *   where: {
   *     // ... filter to delete one Seating
   *   }
   * })
   * 
   */
  delete<T extends SeatingDeleteArgs>(args: Prisma.SelectSubset<T, SeatingDeleteArgs<ExtArgs>>): Prisma.Prisma__SeatingClient<runtime.Types.Result.GetResult<Prisma.$SeatingPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Seating.
   * @param {SeatingUpdateArgs} args - Arguments to update one Seating.
   * @example
   * // Update one Seating
   * const seating = await prisma.seating.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends SeatingUpdateArgs>(args: Prisma.SelectSubset<T, SeatingUpdateArgs<ExtArgs>>): Prisma.Prisma__SeatingClient<runtime.Types.Result.GetResult<Prisma.$SeatingPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Seatings.
   * @param {SeatingDeleteManyArgs} args - Arguments to filter Seatings to delete.
   * @example
   * // Delete a few Seatings
   * const { count } = await prisma.seating.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends SeatingDeleteManyArgs>(args?: Prisma.SelectSubset<T, SeatingDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Seatings.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SeatingUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Seatings
   * const seating = await prisma.seating.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends SeatingUpdateManyArgs>(args: Prisma.SelectSubset<T, SeatingUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Seatings and returns the data updated in the database.
   * @param {SeatingUpdateManyAndReturnArgs} args - Arguments to update many Seatings.
   * @example
   * // Update many Seatings
   * const seating = await prisma.seating.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Seatings and only return the `id`
   * const seatingWithIdOnly = await prisma.seating.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends SeatingUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, SeatingUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SeatingPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Seating.
   * @param {SeatingUpsertArgs} args - Arguments to update or create a Seating.
   * @example
   * // Update or create a Seating
   * const seating = await prisma.seating.upsert({
   *   create: {
   *     // ... data to create a Seating
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Seating we want to update
   *   }
   * })
   */
  upsert<T extends SeatingUpsertArgs>(args: Prisma.SelectSubset<T, SeatingUpsertArgs<ExtArgs>>): Prisma.Prisma__SeatingClient<runtime.Types.Result.GetResult<Prisma.$SeatingPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Seatings.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SeatingCountArgs} args - Arguments to filter Seatings to count.
   * @example
   * // Count the number of Seatings
   * const count = await prisma.seating.count({
   *   where: {
   *     // ... the filter for the Seatings we want to count
   *   }
   * })
  **/
  count<T extends SeatingCountArgs>(
    args?: Prisma.Subset<T, SeatingCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], SeatingCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Seating.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SeatingAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends SeatingAggregateArgs>(args: Prisma.Subset<T, SeatingAggregateArgs>): Prisma.PrismaPromise<GetSeatingAggregateType<T>>

  /**
   * Group by Seating.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SeatingGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends SeatingGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: SeatingGroupByArgs['orderBy'] }
      : { orderBy?: SeatingGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, SeatingGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetSeatingGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Seating model
 */
readonly fields: SeatingFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Seating.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__SeatingClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  orders<T extends Prisma.Seating$ordersArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Seating$ordersArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$OrderPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Seating model
 */
export interface SeatingFieldRefs {
  readonly id: Prisma.FieldRef<"Seating", 'Int'>
  readonly name: Prisma.FieldRef<"Seating", 'String'>
  readonly isDeleted: Prisma.FieldRef<"Seating", 'Boolean'>
  readonly concurrencyVersion: Prisma.FieldRef<"Seating", 'String'>
}
    

// Custom InputTypes
/**
 * Seating findUnique
 */
export type SeatingFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Seating
   */
  select?: Prisma.SeatingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Seating
   */
  omit?: Prisma.SeatingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SeatingInclude<ExtArgs> | null
  /**
   * Filter, which Seating to fetch.
   */
  where: Prisma.SeatingWhereUniqueInput
}

/**
 * Seating findUniqueOrThrow
 */
export type SeatingFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Seating
   */
  select?: Prisma.SeatingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Seating
   */
  omit?: Prisma.SeatingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SeatingInclude<ExtArgs> | null
  /**
   * Filter, which Seating to fetch.
   */
  where: Prisma.SeatingWhereUniqueInput
}

/**
 * Seating findFirst
 */
export type SeatingFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Seating
   */
  select?: Prisma.SeatingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Seating
   */
  omit?: Prisma.SeatingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SeatingInclude<ExtArgs> | null
  /**
   * Filter, which Seating to fetch.
   */
  where?: Prisma.SeatingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Seatings to fetch.
   */
  orderBy?: Prisma.SeatingOrderByWithRelationInput | Prisma.SeatingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Seatings.
   */
  cursor?: Prisma.SeatingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Seatings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Seatings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Seatings.
   */
  distinct?: Prisma.SeatingScalarFieldEnum | Prisma.SeatingScalarFieldEnum[]
}

/**
 * Seating findFirstOrThrow
 */
export type SeatingFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Seating
   */
  select?: Prisma.SeatingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Seating
   */
  omit?: Prisma.SeatingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SeatingInclude<ExtArgs> | null
  /**
   * Filter, which Seating to fetch.
   */
  where?: Prisma.SeatingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Seatings to fetch.
   */
  orderBy?: Prisma.SeatingOrderByWithRelationInput | Prisma.SeatingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Seatings.
   */
  cursor?: Prisma.SeatingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Seatings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Seatings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Seatings.
   */
  distinct?: Prisma.SeatingScalarFieldEnum | Prisma.SeatingScalarFieldEnum[]
}

/**
 * Seating findMany
 */
export type SeatingFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Seating
   */
  select?: Prisma.SeatingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Seating
   */
  omit?: Prisma.SeatingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SeatingInclude<ExtArgs> | null
  /**
   * Filter, which Seatings to fetch.
   */
  where?: Prisma.SeatingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Seatings to fetch.
   */
  orderBy?: Prisma.SeatingOrderByWithRelationInput | Prisma.SeatingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Seatings.
   */
  cursor?: Prisma.SeatingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Seatings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Seatings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Seatings.
   */
  distinct?: Prisma.SeatingScalarFieldEnum | Prisma.SeatingScalarFieldEnum[]
}

/**
 * Seating create
 */
export type SeatingCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Seating
   */
  select?: Prisma.SeatingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Seating
   */
  omit?: Prisma.SeatingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SeatingInclude<ExtArgs> | null
  /**
   * The data needed to create a Seating.
   */
  data: Prisma.XOR<Prisma.SeatingCreateInput, Prisma.SeatingUncheckedCreateInput>
}

/**
 * Seating createMany
 */
export type SeatingCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Seatings.
   */
  data: Prisma.SeatingCreateManyInput | Prisma.SeatingCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Seating createManyAndReturn
 */
export type SeatingCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Seating
   */
  select?: Prisma.SeatingSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Seating
   */
  omit?: Prisma.SeatingOmit<ExtArgs> | null
  /**
   * The data used to create many Seatings.
   */
  data: Prisma.SeatingCreateManyInput | Prisma.SeatingCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Seating update
 */
export type SeatingUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Seating
   */
  select?: Prisma.SeatingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Seating
   */
  omit?: Prisma.SeatingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SeatingInclude<ExtArgs> | null
  /**
   * The data needed to update a Seating.
   */
  data: Prisma.XOR<Prisma.SeatingUpdateInput, Prisma.SeatingUncheckedUpdateInput>
  /**
   * Choose, which Seating to update.
   */
  where: Prisma.SeatingWhereUniqueInput
}

/**
 * Seating updateMany
 */
export type SeatingUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Seatings.
   */
  data: Prisma.XOR<Prisma.SeatingUpdateManyMutationInput, Prisma.SeatingUncheckedUpdateManyInput>
  /**
   * Filter which Seatings to update
   */
  where?: Prisma.SeatingWhereInput
  /**
   * Limit how many Seatings to update.
   */
  limit?: number
}

/**
 * Seating updateManyAndReturn
 */
export type SeatingUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Seating
   */
  select?: Prisma.SeatingSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Seating
   */
  omit?: Prisma.SeatingOmit<ExtArgs> | null
  /**
   * The data used to update Seatings.
   */
  data: Prisma.XOR<Prisma.SeatingUpdateManyMutationInput, Prisma.SeatingUncheckedUpdateManyInput>
  /**
   * Filter which Seatings to update
   */
  where?: Prisma.SeatingWhereInput
  /**
   * Limit how many Seatings to update.
   */
  limit?: number
}

/**
 * Seating upsert
 */
export type SeatingUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Seating
   */
  select?: Prisma.SeatingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Seating
   */
  omit?: Prisma.SeatingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SeatingInclude<ExtArgs> | null
  /**
   * The filter to search for the Seating to update in case it exists.
   */
  where: Prisma.SeatingWhereUniqueInput
  /**
   * In case the Seating found by the `where` argument doesn't exist, create a new Seating with this data.
   */
  create: Prisma.XOR<Prisma.SeatingCreateInput, Prisma.SeatingUncheckedCreateInput>
  /**
   * In case the Seating was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.SeatingUpdateInput, Prisma.SeatingUncheckedUpdateInput>
}

/**
 * Seating delete
 */
export type SeatingDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Seating
   */
  select?: Prisma.SeatingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Seating
   */
  omit?: Prisma.SeatingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SeatingInclude<ExtArgs> | null
  /**
   * Filter which Seating to delete.
   */
  where: Prisma.SeatingWhereUniqueInput
}

/**
 * Seating deleteMany
 */
export type SeatingDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Seatings to delete
   */
  where?: Prisma.SeatingWhereInput
  /**
   * Limit how many Seatings to delete.
   */
  limit?: number
}

/**
 * Seating.orders
 */
export type Seating$ordersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Order
   */
  select?: Prisma.OrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Order
   */
  omit?: Prisma.OrderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrderInclude<ExtArgs> | null
  where?: Prisma.OrderWhereInput
  orderBy?: Prisma.OrderOrderByWithRelationInput | Prisma.OrderOrderByWithRelationInput[]
  cursor?: Prisma.OrderWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.OrderScalarFieldEnum | Prisma.OrderScalarFieldEnum[]
}

/**
 * Seating without action
 */
export type SeatingDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Seating
   */
  select?: Prisma.SeatingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Seating
   */
  omit?: Prisma.SeatingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SeatingInclude<ExtArgs> | null
}
