export const displayNames = {
  user: "Người dùng",
  role: "Vị trí",
  photo: "Hình ảnh",
  announcement: "Thông báo",
  id: "Mã số",
  name: "Tên",
  account: "Tài khoản",
  userName: "Tên đăng nhập",
  password: "Mật khẩu",
  currentPassword: "Mật khẩu hiện tại",
  newPassword: "Mật khẩu mới",
  status: "Tình trạng",
  createdDateTime: "Ngày tạo",
  lastUpdatedDateTime: "Ngày cập nhật",
  createdUser: "Nhân viên tạo",
  lastUpdatedUser: "Nhân viên cập nhật",
  note: "Ghi chú",
  introducer: "Người giới thiệu",
  description: "Mô tả",
  unit: "Đơn vị",
  defaultAmountBeforeVatPerUnit: "Giá niêm yết",
  defaultVatPercentagePerUnit: "Thuế VAT mặc định",
  amount: "Số tiền",
  amountBeforeVatPerUnit: "Số tiền trước thuế",
  vatAmount: "Thuế VAT",
  vatPercentagePerUnit: "Hệ số thuế",
  seating: "Bàn ăn",
  menuItem: "Món ăn",
  index: "Chỉ mục",
  totalAmount: "Tổng giá tiền",
  paidAmount: "Số tiền đã thanh toán",
  startingDateTime: "Ngày giờ bắt đầu",
  endingDateTime: "Ngày giờ kết thúc",
  category: "Phân loại",
  isPinned: "Được đánh dấu",
  order: "Gọi món",
  orderItem: "Mục gọi món",
  sortByFieldName: "Trường sắp xếp",
  sortByAscending: "Thứ tự sắp xếp",
  searchByField: "Trường tìm kiếm",
  searchContent: "Nội dung tìm kiếm",
  page: "Trang",
  resultsPerPage: "Kết quả mỗi trang",
  pageCount: "Số trang",
  resultsCount: "Số kết quả",
  results: "Kết quả",
  thumbnailFile: "File ảnh xem trước",
  rangeFrom: "Khoảng bắt đầu",
  rangeTo: "Khoảng kết thúc",
  rangeType: "Kiểu khoảng",
  rangeLength: "Độ dài khoảng",
  file: "File",
  updatedReason: "Lý do chỉnh sửa",
  debt: "Khoản nợ",
  debtIncurrence: "Ghi nợ",
  debtPayment: "Thanh toán nợ",
  debtRemainingAmount: "Số nợ còn lại",
  monthlyStats: "Thống kê tháng",
  month: "Tháng",
  monthCount: "Số lượng tháng",
  dayCount: "Số lượng ngày",
  year: "Năm",
  dailyStats: "Thống kê theo ngày",
  recordedDate: "Ngày thống kê",
  recordedMonth: "Tháng thống kê",
  recordedYear: "Năm thống kê",
  recordedMonthAndYear: "Tháng và năm thông kê",
  intervalInMinutes: "Số phút hiệu lực",
  statsDate: "Ngày thống kê",
  home: "Trang chủ",
  creteria: "Tiêu chí",
  count: "Số lượng",
  date: "Ngày",
  day: "Ngày",
  purchasedAmount: "Số tiền đã mua",
  purchasedTransactionCount: "Số lượng giao dịch mua",
  quantity: "Số lượng",
  default: "Mặc định",
  timeRangeUnitType: "Kiểu đơn vị khung thời gian",
  timeRangeUnitCount: "Số lượng đơn vị khung thời gian",
};
